### ISSUE TITLE
Thumbnails Carousel breaks when is more thumbs

### ISSUE THREAD

**Issue by rafalradomski** [mdbootstrap/bootstrap-material-design#1]
http://mdbootstrap.com/javascript/carousel/

![https://s3.postimg.io/d1efrt8ht/thumbnail.jpg](https://s3.postimg.io/d1efrt8ht/thumbnail.jpg)

**Comment by mdbootstrap** [comment]
We'll fix it in the next update.

**Comment by rafalradomski** [comment]
Any progress on that?

**Comment by mattonit** [comment]
@rafalradomski unfortunately, the problem is still on our TODO list

**Comment by bf** [comment]
Any update?

**Comment by pglejzer** [comment]
It's an old topic, it was fixed a long time ago.
