### ISSUE TITLE
WOW causes issues with AddThis Share Buttons

### ISSUE THREAD

**Issue by alanmac** [mdbootstrap/bootstrap-material-design#100]
MDB Version: MDB PRO 4.4.0 beta

When using the Floating share button tool from addthis.com, dom additions are made and WOW throws an exception because the className is an SVGAnimatedString.

Should there be a check for this to ensure that the split can be performed?

![image](https://user-images.githubusercontent.com/1780374/31247427-78646b12-aa08-11e7-8a72-f60ad98c9051.png)

**Comment by mattonit** [comment]
Please, try to upgrade your version of MDB and let us know if you're still facing the issue

**Comment by alanmac** [comment]
Will do, I'll let you know.
