### ISSUE TITLE
[Feature Request] Range Input - Left Side should be filled

### ISSUE THREAD

**Issue by Juchar** [mdbootstrap/bootstrap-material-design#101]
It would be nice if the left side of the [Range Slider](https://mdbootstrap.com/components/inputs/#range) would be filled with a specified color. See Angular Material as an example.

MDB:
![image](https://user-images.githubusercontent.com/14292982/31327905-5b7f3956-acd2-11e7-948d-ee3bf942a05c.png)

Angular Material [(click)](https://material.angular.io/components/slider/examples):
![image](https://user-images.githubusercontent.com/14292982/31327925-7d3e9ff0-acd2-11e7-95db-6c5d97a35814.png)

**Comment by mattonit** [comment]
Thank you for the suggestion. I added this to our TODO list
