### ISSUE TITLE
Input Label exceeds md-form

### ISSUE THREAD

**Issue by Juchar** [mdbootstrap/bootstrap-material-design#102]
Using an input the label will exceed the wrapping `<div class="md-form">`.
This behaviour can be observed in the [examples](https://mdbootstrap.com/angular/components/inputs/#input-fields).

By consequence it is complicated to do a good layouting (e.g. having a heading before will cause overlaps).

Of course you can overcome this by adding a margin to the `<div class="md-form">`, but I assume that is not the correct, **clean way** of doing it.

Screenshots:
![image](https://user-images.githubusercontent.com/14292982/31428292-9c578d68-ae6a-11e7-8929-25ff5ca6a715.png)
![image](https://user-images.githubusercontent.com/14292982/31428329-b3184812-ae6a-11e7-91cc-20d3b683072c.png)

**Comment by mattonit** [comment]
It was intended. I've just suggested our designers to remove this so this may change in next release

**Comment by faisalnoufal** [comment]
Yes, please remove and add the place holders. Example: 
`<div class="form-sm">
    <i class="fa fa-user" aria-hidden="true"></i>
          <input type="text" id="form19" placeholder="Name" class="form-control" name="Name">              
</div>`

**Comment by faisalnoufal** [comment]
Yes, please remove the class md-form and label and add placeholders instead. 
```
<div class="form-sm">
    <i class="fa fa-user" aria-hidden="true"></i>
          <input type="text" id="form19" placeholder="Name" class="form-control" name="Name">              
</div>
```
