### ISSUE TITLE
Filled-In Checkbox - Label not centered vertically

### ISSUE THREAD

**Issue by Juchar** [mdbootstrap/bootstrap-material-design#103]
The label of a filled in Checkbox is not centered vertically to the actual checkbox.
Instead the label is aligned with the bottom of the box.

![image](https://user-images.githubusercontent.com/14292982/31428645-cc4961da-ae6b-11e7-81c7-d6f14ed8d610.png)

**Comment by mattonit** [comment]
This will be fixed in the next release

**Comment by bumblebear** [comment]
Not sure if this is relevant - when the text is looong, the tick anchors to the top, while the filled-in box anchors to the bottom.
![screen shot 2017-12-06 at 6 15 51 pm](https://user-images.githubusercontent.com/5379672/33649315-8ba9e574-dab1-11e7-856a-84bcde8d764b.png)

**Comment by Martussky** [comment]
We will fix both of these issues in next release which we are working now.
