### ISSUE TITLE
Error with forms-free.js - _$hiddenDiv is not defined - MDB PRO 4.4.1

### ISSUE THREAD

**Issue by alanmac** [mdbootstrap/bootstrap-material-design#104]
I'm using MDB PRO 4.4.1 and building the js from chosen modules.

forms-free.js is causing an error as seen in attached.

I added a check to account for hiddenDiv not being there. Can this be fixed in the core please?

![image](https://user-images.githubusercontent.com/1780374/31589460-c30ee676-b1f9-11e7-9328-8561a6413ecf.png)

Thanks.

**Comment by mattonit** [comment]
Could you please tell us which modules are added?

**Comment by alanmac** [comment]
sorry for not getting back sooner

modules used:

animations.js
buttons.js
card-reveal.js
cards.js
character-counter.js
chips.js
collapsible.js
dropdown.js
enhanced-modals.js
file-input.js
forms-free.js
hammer.js
jarallax-video.js
jarallax.js
jquery.easing.js
jquery.easypiechart.js
jquery.hammer.js
jquery.sticky.js
lightbox.js
material-select.js
mdb-autocomplete.js
preloading.js
range-input.js
scrollbar.js
scrolling-navbar.js
sidenav.js
smooth-scroll.js
toastr.js
velocity.min.js
waves.js
wow.js
