### ISSUE TITLE
sideNav closeOnClick - sn is not defined

### ISSUE THREAD

**Issue by coreystinson2** [mdbootstrap/bootstrap-material-design#105]
I believe there to be a typo in `mdb.js` file when using sideNav with `closeOnClick: true`.

```
17923 if (this.options.closeOnClick === true) {
17924     this.menu_id.on("click", "a:not(.collapsible-header)", function () {
17925         sn.removeMenu();
17926     });
17927 }
```

`sn` is not referenced anywhere and should be replaced with `_this` as referenced elsewhere within the component.
```
17923 if (this.options.closeOnClick === true) {
17924     this.menu_id.on("click", "a:not(.collapsible-header)", function () {
17925         _this.removeMenu();
17926     });
17927 }
```

**Steps to reproduce**
Copy the html provided under basic usage: https://mdbootstrap.com/javascript/sidenav/

Initialize sideNav with following option
```
$('.button-collapse').sideNav({closeOnClick: true});
```

**Comment by mattonit** [comment]
What's your version of MDB?

**Comment by mattonit** [comment]
closed due to no response
