### ISSUE TITLE
$image-path not used in _masks.scss, breaks sass compile

### ISSUE THREAD

**Issue by dkent600** [mdbootstrap/bootstrap-material-design#106]
See the conversation on your forum, [here](https://mdbootstrap.com/support/can-we-get-path-variable-in-sass/).

Trying to compile for sass generates the error:

"Cannot find module “../img/..”"

There already exists a `$image-path` that we should be able to use to provide the path.  It is already being used in `_carousel-basic`.  But it is not being used in `_masks`, hence the error.

The current solution is absolutely not reasonable, expecting us to "customize" mdbootstrap by modifying files located in the node_modules folder.

Using mdbootstrap v4.4.1.

**Comment by cmckni3** [comment]
I am running into the same issues on 4.4.3.

**Comment by smolenski-mikolaj** [comment]
Thank for Your message. We'll try to solve that issue.

Regards

**Comment by mattonit** [comment]
@cmckni3 have you tried with 4.5.0?

**Comment by cmckni3** [comment]
@mattonit negative, switched projects because I needed to release a project in a week and 3 projects total in 16 weeks.

**Comment by darioblanco** [comment]
I can't understand why such a small fix is still not addressed in 6 months. Importing this via sass seems a very important feature to me.

**Comment by rochapablo** [comment]
News?

**Comment by Martussky** [comment]
Hi,
we've fixed that.
Best,
Marta
