### ISSUE TITLE
Instructions on overriding roboto font path

### ISSUE THREAD

**Issue by cmckni3** [mdbootstrap/bootstrap-material-design#112]
Add override for sass builds into README.

**Comment by JStrebeyko** [comment]
The way to do what exactly would you like to see in the README?

**Comment by cmckni3** [comment]
Does the font path for Roboto need to be overridden for Sass builds to find it? This is common with Font Awesome. I could not get it to build using Sass due to #106

**Comment by jhourlad** [comment]
What's the resolution to this? Roboto font files in the production package is too huge.
