### ISSUE TITLE
Consider adding stylelint.

### ISSUE THREAD

**Issue by phpeek** [mdbootstrap/bootstrap-material-design#113]
Are You guys interested in adding `stylelint` for linting `scss` files into this project ?

We could use the same configuration as in https://github.com/twbs/bootstrap/blob/v4-dev/build/.stylelintrc

I'm happy to give it some time, but wanted to make sure this project is not using `stylelint` on purpose.

**Comment by mattonit** [comment]
We also use stylelint for our scss files. Our configuration is similar to Bootstrap's one, but we have added some customization
