### ISSUE TITLE
massive base mdb.js needs to be split up and requirements documented

### ISSUE THREAD

**Issue by NathanQ** [mdbootstrap/bootstrap-material-design#115]
Troubleshooting the 14k line copypasta mdb.js file is wholly unmanageable. Please consider documenting each module(optional) scripts dependencies so features can be cherry-picked if so desired.

**Comment by ryanrishi** [comment]
+1

This was acknowledged in #62 , but I don't think it has been addressed yet. I might fork it and get it set up...

**Comment by JStrebeyko** [comment]
Thanks for reaching out, @NathanQ. We definitely agree, as we follow this logical principle within SCSS files and MDB React / Vue version. It's has to be done, although there are no plans to do so in the nearest future. All help would be greatly appreciated! :)
