### ISSUE TITLE
    tsconfig configuration noImplicitAny and strictNullChecks gives error on compilation

### ISSUE THREAD

**Issue by sandip12081992** [mdbootstrap/bootstrap-material-design#116]
tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": false
  }
}

```

Error on console
ERROR in node_modules/angular-bootstrap-md/inputs/active.class.ts(10,3): error TS2322: Type 'null' is not assignable to type 'ElementRef'.
node_modules/angular-bootstrap-md/inputs/active.class.ts(11,3): error TS2322: Type 'null' is not assignable to type 'ElementRef'.
node_modules/angular-bootstrap-md/inputs/active.class.ts(12,3): error TS2322: Type 'null' is not assignable to type 'Element'.
node_modules/angular-bootstrap-md/inputs/equal-validator.directive.ts(38,14): error TS2531: Object is possibly 'null'.
node_modules/angular-bootstrap-md/inputs/equal-validator.directive.ts(51,5): error TS2322: Type 'null' is not assignable to type '{ [key: string]: any; }'.
node_modules/angular-bootstrap-md/inputs/input-validate.directive.ts(37,23): error TS2532: Object is possibly 'undefined'.
node_modules/angular-bootstrap-md/inputs/input-validate.directive.ts(37,23): error TS2531: Object is possibly 'null'.
node_modules/angular-bootstrap-md/inputs/input-validate.directive.ts(37,51): error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.
node_modules/angular-bootstrap-md/dropdown/dropdown-toggle.directive.ts(14,3): error TS2322: Type 'null' is not assignable to type 'boolean'.
node_modules/angular-bootstrap-md/dropdown/dropdown-toggle.directive.ts(50,36): error TS2322: Type 'true | null' is not assignable to type 'boolean'.
  Type 'null' is not assignable to type 'boolean'.
node_modules/angular-bootstrap-md/utils/positioning/positioning.service.ts(41,31): error TS2345: Argument of type 'string | HTMLElement | ElementRef | undefined' is not assignable to parameter of type 'string | HTMLElement | ElementRef'.
  Type 'undefined' is not assignable to type 'string | HTMLElement | ElementRef'.
node_modules/angular-bootstrap-md/utils/positioning/positioning.service.ts(42,31): error TS2345: Argument of type 'string | HTMLElement | ElementRef | undefined' is not assignable to parameter of type 'string | HTMLElement | ElementRef'.
  Type 'undefined' is not assignable to type 'string | HTMLElement | ElementRef'.
node_modules/angular-bootstrap-md/utils/positioning/positioning.service.ts(43,10): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
node_modules/angular-bootstrap-md/utils/triggers.ts(58,32): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.class.ts(99,26): error TS2532: Object is possibly 'undefined'.
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.class.ts(100,27): error TS2532: Object is possibly 'undefined'.
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.class.ts(112,8): error TS2322: Type 'null' is not assignable to type 'ComponentRef<T>'.
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.class.ts(133,12): error TS2531: Object is possibly 'null'.
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.class.ts(180,10): error TS2322: Type 'null' is not assignable to type 'ContentRef'.
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.class.ts(181,10): error TS2322: Type 'null' is not assignable to type 'ComponentRef<T>'.
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.class.ts(215,14): error TS2532: Object is possibly 'undefined'.
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.class.ts(216,14): error TS2532: Object is possibly 'undefined'.
node_modules/angular-bootstrap-md/utils/linked-list.class.ts(35,7): error TS2322: Type 'undefined' is not assignable to type 'T'.
node_modules/angular-bootstrap-md/utils/linked-list.class.ts(155,7): error TS2322: Type 'undefined' is not assignable to type 'T'.
node_modules/angular-bootstrap-md/utils/linked-list.class.ts(172,7): error TS2322: Type 'undefined' is not assignable to type 'T'.
node_modules/angular-bootstrap-md/utils/linked-list.class.ts(241,12): error TS2454: Variable 'result' is used before being assigned.
node_modules/angular-bootstrap-md/utils/linked-list.class.ts(254,12): error TS2454: Variable 'result' is used before being assigned.
node_modules/angular-bootstrap-md/carousel/carousel.component.ts(52,3): error TS2322: Type 'null' is not assignable to type 'ElementRef'.
node_modules/angular-bootstrap-md/carousel/carousel.component.ts(138,8): error TS2322: Type 'undefined'is not assignable to type 'number'.
node_modules/angular-bootstrap-md/carousel/carousel.component.ts(154,12): error TS2322: Type 'undefined' is not assignable to type 'number'.
node_modules/angular-bootstrap-md/carousel/slide.component.ts(27,3): error TS2322: Type 'null' is not assignable to type 'ElementRef'.
node_modules/angular-bootstrap-md/modals/modal.directive.ts(110,5): error TS2322: Type 'undefined' is not assignable to type 'ModalOptions'.
node_modules/angular-bootstrap-md/modals/modal.directive.ts(136,5): error TS2322: Type 'null' is not assignable to type 'string'.
node_modules/angular-bootstrap-md/modals/modal.service.ts(32,74): error TS2345: Argument of type 'null'is not assignable to parameter of type 'ElementRef'.
node_modules/angular-bootstrap-md/modals/modal.service.ts(41,5): error TS2322: Type 'null' is not assignable to type 'string'.
node_modules/angular-bootstrap-md/modals/modal.service.ts(58,55): error TS2365: Operator '===' cannot be applied to types 'false | undefined' and '"static"'.
node_modules/angular-bootstrap-md/modals/modal.service.ts(117,5): error TS2322: Type 'null' is not assignable to type 'ComponentRef<ModalBackdropComponent>'.
node_modules/angular-bootstrap-md/modals/modal.service.ts(156,67): error TS2345: Argument of type 'null' is not assignable to parameter of type 'ElementRef'.

**Comment by mdbootstrap** [comment]
Hi @sandip12081992 , it looks like you opened a issue in wrong project. I guess you were referring to: https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design

Regarding your issue. At the moment we are not compatible with  "noImplicitAny": true nor     "strictNullChecks": true, however we are working on it. Within coming release we have make our code compatible with: 
   "noUnusedLocals": true,
    "noUnusedParameters": true,
