### ISSUE TITLE
build this project with tsconfig => noImplicitAny: "true"

### ISSUE THREAD

**Issue by sandip12081992** [mdbootstrap/bootstrap-material-design#117]
I got a error in input-validate.directive.ts at line 37.
const inputType = event.srcElement.attributes.['type'].nodeValue as string;
You should change this line with:
    const inputType = event.srcElement.attributes.getNamedItem('type').nodeValue as string;
or,
    const inputType = event.targetElement.attributes.getNamedItem('type').nodeValue as string;

Not every Angular developer like use of  typescript **"any"** in project. I strictly disallow use of **any** in Angular project. We want a modular more organised project thats why we are using Angular.

**Comment by mdbootstrap** [comment]
Hi @sandip12081992 , it looks like you opened a issue in wrong project. I guess you were referring to: https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design

Regarding your issue. At the moment we are not compatible with "noImplicitAny": true nor "strictNullChecks": true, however we are working on it. Within coming release we have make our code compatible with:
"noUnusedLocals": true,
"noUnusedParameters": true,
