### ISSUE TITLE
Box shadow color seems to keep original color when overridden

### ISSUE THREAD

**Issue by EtienneDG** [mdbootstrap/bootstrap-material-design#118]
Hello,

Version : 
 "bootstrap": "4.0.0-beta.2",
 "mdbootstrap": "4.4.3",

I tried overridding colors by using the _custom.scss file, example with this Sass code : 
```
$info-color: yellow;
$danger-color: blue;
```
The color of the button changes alright but when the button is active the box shadow still has the "previous color" : 
![mdb_box_shadow_issue](https://user-images.githubusercontent.com/5869860/32845817-0afc94e4-ca26-11e7-8ac0-2da9efe7b2bc.PNG)

Checking the docs the issue is also there on regular non overridden buttons that are not the same or not part of bootstrap theme (no box shadow for btn-default when active). 
![mdb_box_shadow_doc](https://user-images.githubusercontent.com/5869860/32847579-a8b89206-ca2a-11e7-9d3e-d120dffd9124.PNG)

Going through bootstrap implementation they have special mixin 'box-shadow' (https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_box-shadow.scss) that they use for this purpose.

I'm personnaly not a fan of the colored box shadow when active, I find the wave effect and the clear of the grey box shadow enough.

I guess there are two solutions : 
```
.btn {
    &:active {
        box-shadow: none;
    }
}
```

Or adding a mixin and calling it in _button.sccs : 
```
@each $btn-name, $color-value in $material-colors {
  @include make-button($btn-name, $color-value);
  @include make-outline-button($btn-name, $color-value);
  @include box-shadow($btn-name, $color-value);
}
```

Cheers.

**Comment by mattonit** [comment]
Thanks for the suggestion. We'll take a look at this!
