### ISSUE TITLE
btn-light and btn-warning text color is white by default

### ISSUE THREAD

**Issue by StupidSexyJake** [mdbootstrap/bootstrap-material-design#119]
When using .btn-light or .btn-warning button classes, the bootstrap mixin that creates a dark contrasting text color for the button is overwritten by MD Bootstrap's .btn class which simply specifies that the text color is to be white. So if you use .btn-light, it creates a button that has both a white background _and_ white text.

Mixin from Bootstrap that creates the contrasting color: [bootstrap/scss/mixins/_buttons.scss (line 7)](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_buttons.scss)

```
// Button variants
//
// Easily pump out default styles, as well as :hover, :focus, :active,
// and disabled options for all buttons

@mixin button-variant($background, $border, $hover-background: darken($background, 7.5%), $hover-border: darken($border, 10%), $active-background: darken($background, 10%), $active-border: darken($border, 12.5%)) {
  color: color-yiq($background);
  @include gradient-bg($background);
  border-color: $border;
  @include box-shadow($btn-box-shadow);

  @include hover {
    color: color-yiq($hover-background);
    @include gradient-bg($hover-background);
    border-color: $hover-border;
  }
```

Chrome Inspector showing that it's being overwritten:
![image](https://user-images.githubusercontent.com/23021947/33105719-5866e384-cf7a-11e7-87ea-2ccf74011cba.png)

Where it's being overwritten:
![image](https://user-images.githubusercontent.com/23021947/33105738-74d85796-cf7a-11e7-9288-74efc5d9aae4.png)

Workaround:
Create .btn-light class in css/styles.css and set text color manually - must use !important.

```
.btn-light, .btn-warning {
	color: #111 !important;
}
```

**Comment by JStrebeyko** [comment]
Thanks for reaching out! We're on it.
