### ISSUE TITLE
Bootstrap Flexbox grid

### ISSUE THREAD

**Issue by AlvSovereign** [mdbootstrap/bootstrap-material-design#12]
Hi

I cannot figure out how to use the bootstrap flexbox grid in MDBootstrap. Is this something you have turned off?

**Comment by bf** [comment]
Slow answer for a paid bootstrap framework..

**Comment by EldoranDev** [comment]
Did you change or overwrite "enable flex" ? https://github.com/mdbootstrap/bootstrap-material-design/blob/master/sass/mdb/free/data/_variables-b4.scss#L46

**Comment by mattonit** [comment]
We didn't change anything with Bootstrap. Since the alpha 6 use flex by default new MDB 4.3.0 will be rewritten to flexbox
