### ISSUE TITLE
Need a multi item carousel in which items slides one by one

### ISSUE THREAD

**Issue by bhony-bharath** [mdbootstrap/bootstrap-material-design#121]
I'm using MDB for multiple projects and having a multi-item carousel in which the items slide one by one could be a great addition to the already beautiful carousel examples to present contents.

eg: https://codepen.io/MarkitDigital/pen/ZpEByz

**Comment by mattonit** [comment]
That's great! We'll add this to our carousel ;)

**Comment by mcwnuq** [comment]
nice, i'm waiting

**Comment by Martussky** [comment]
Hi,
there is this carousel: https://mdbootstrap.com/docs/jquery/javascript/carousel/#multi-item-carousel-v2.
Best, Marta
