### ISSUE TITLE
Production web page conflicts

### ISSUE THREAD

**Issue by jjcc1421** [mdbootstrap/bootstrap-material-design#122]
Hey do you have an issue in your production web page on  https://mdbootstrap.com/getting-started/
![image](https://user-images.githubusercontent.com/4220107/33468377-c995cbaa-d629-11e7-86ff-c50768f1649c.png)
![image](https://user-images.githubusercontent.com/4220107/33468448-60f6ff78-d62a-11e7-8367-62bd0ee991da.png)

**Comment by mattonit** [comment]
Thank you for noticing. It's already fixed ;)
