### ISSUE TITLE
Support Font Awesome 5

### ISSUE THREAD

**Issue by s1awa** [mdbootstrap/bootstrap-material-design#124]
[Font Awesome 5](https://fontawesome.com/) was released recently.

css file has some references to Font Awesome 4
`.fa`

Font Awesome 5 has new class names
`.fas`
`.far`
`.fal`
`.fab`

**Comment by mattonit** [comment]
our team is already checking this out ;) I hope we'll migrate to FA5 soon ;)

**Comment by s1awa** [comment]
What works good for me is just to keep .fa css class even though it is not used in Font Awesome 5

`<i class="fa fas fa-user" aria-hidden="true"></i>`

**Comment by s1awa** [comment]
I added those new classes to all scss files that used `.fa` class, compiled them and it works great.

**Comment by mattonit** [comment]
I still don't have good news

**Comment by mraible** [comment]
How about now? ;)

**Comment by mattonit** [comment]
still no :(

**Comment by s1awa** [comment]
It is not so hard to patch the mdb.css, just search for .fa and copy the whole selector after a comma and change the class, do it for each of the classes (.fas, .far, .fal, .fab)

e.g.
```
.contact-section .contact .fa {
    color: #6b89a5;
}
```

needs to be changed to

```
.contact-section .contact .fa, .contact-section .contact .fal, .contact-section .contact .far, .contact-section .contact .fas, .contact-section .contact .fab {
    color: #6b89a5;
}
```

Then you can use FA4 or FA5 as you wish

**Comment by s1awa** [comment]
https://github.com/mdbootstrap/bootstrap-material-design/releases/tag/4.6.0

Migration to Font Awesome 5 - change of the icon syntax

In this release we have migrated to the newest version of Font Awesome. It rings a lot of new features and hundreds of new icons. Hoverer, MDB 4.6.0. requires a migration, because the syntax of the icons has changed and it's not compatible with the previous version.
