### ISSUE TITLE
Buttons with javascript click event work intermittently in Safari

### ISSUE THREAD

**Issue by NathanQ** [mdbootstrap/bootstrap-material-design#128]
Any button with a click event doesn't work all the time.
examples
```
// jquery
$('#do-stuff-trigger').on('click', function (event) {
    event.preventDefault();
    doStuff();
});
```
or 
```
// vanilla
document.getElementById('do-stuff-trigger').addEventListener('click', function( event ) {
    doStuff();
}, false);
```

When the `.btn` class is removed from the `#do-stuff-trigger` where MDB ignores it by not adding it's `.waves-effect .waves-light` classes, the click function works every time.

**Comment by smolenski-mikolaj** [comment]
Hi NathanQ,

Please comment following lines in mdb.js file and check if the problem still exists:

Lines 14012 - 14019
```
Waves.attach('.btn:not(.btn-flat), .btn-floating', ['waves-light']);
Waves.attach('.btn-flat', ['waves-effect']);
Waves.attach('.view .mask', ['waves-light']);
Waves.attach('.waves-light', ['waves-light']);
Waves.attach('.navbar-nav a:not(.navbar-brand), .nav-icons li a, .navbar form, .nav-tabs .nav-item', ['waves-light']);
Waves.attach('.pager li a', ['waves-light']);
Waves.attach('.pagination .page-item .page-link', ['waves-effect']);
Waves.init();
```
Regards

**Comment by NathanQ** [comment]
Thanks @smolenski-mikolaj. My bad. It doesn't seem to be MDB, but rather a WebKit bug https://bugs.webkit.org/show_bug.cgi?id=39620. Sometimes it works, sometimes not. So fucky.

If anyone else experiences it, a fix is doing something like:
```
<button class="btn etc..">
  <span style="display:block; pointer-events: none">Click Me</span>
</button>
```
