### ISSUE TITLE
Charts not working for dynamic value

### ISSUE THREAD

**Issue by surazzarus** [mdbootstrap/bootstrap-material-design#129]
Minimalist charts works fine for the hardcode value but isn't working for the dynamic value.

**Comment by smolenski-mikolaj** [comment]
It should also work for dynamic value. Please read this documentation topic and some issues:

http://www.chartjs.org/docs/latest/developers/updates.html
http://www.chartjs.org/docs/latest/developers/api.html

https://github.com/chartjs/Chart.js/issues/393
https://github.com/chartjs/Chart.js/issues/207

**Comment by surazzarus** [comment]
Unfortunately, it didn't work for me and I had to choose other percent circle.

Anyways thank you for the reply. :)
