### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Dirbaio** [mdbootstrap/bootstrap-material-design#13]
What license is this project under?

I see both bower.json and package.json state this is MIT licensed, but license.pdf is something else. 

If it's MIT, you should include the [MIT license text](https://opensource.org/licenses/MIT) in a license.txt or similar.

If not, you should probably povide an actual license legal text, the PDF is very ambiguous, which is quite worrying for many possible users of this project. (What does "Offer PSD/HTML to users of your service" mean, for example? If a user visits my website, my servers will send HTML to his browser... Is that against the license?)

**Comment by dawidadach** [comment]
Dear Dirbaio, 
MDB license is located in License.pdf file. 

Thanks for letting us know, we have updated package.json and bower.json files pointing to correct license. Regarding PSD/HTML point, we have removed it (it was inherited from our other products by mistake). I hope everything is clear now - you can of course use MDB to create websites for both - personal as well as commercial use.

**Comment by Dirbaio** [comment]
It's quite disappointing that this is not open source. By "Open source" as in having an actual opensource license. I would use this if it was.

The restrictions you outline in the PDF are very unclear and don't inspire confidence. Also why don't you allow using the free version in an opensource project? It's free anyways. 

You should release the free version with an actual open source license, and then have whatever restrictions you want on the paid version. You don't lose anything and you will gain many more users such as me, who are concerned about your weird "license".

**Comment by mdbootstrap** [comment]
Dear Dirbaio, 
thank you for your proposal, however, we want to have a control over distribution of our package. Due to that and few other reasons we need custom license.

**Comment by skylarmt** [comment]
I was considering using this project in an app of mine, but after realizing I can't use it in an open source app, I'm going to look for another option.  It's a real shame, and there's no real reason for the restriction.

**Comment by timperrett** [comment]
@mdbootstrap given mdbootstrap is available on cloudflare, linking to the CDN-distributed, free version is technically not a redistribution by the user. Something akin to dynamic linking in pre-existing legal understanding. Is this a fair reading? Cloudflare location: https://cdnjs.com/libraries/mdbootstrap

FWIW, the License.pdf is more vague than i'd prefer a license to be, and most lawyers would likely have a problem with it. If the intention is to prevent re-distribution or for-profit work, perhaps consider AGPL or an existing license that is understood and documented. Custom licenses that are not modifications or derivations can be very troublesome for users.

**Comment by mdbootstrap** [comment]
Dear @timperrett 
Indeed our intention is to prevent uncontrolled redistribution, while at the same time we do not mind using MDB for commercial purpose. We will take a closer look at AGPL license, thank you.

**Comment by skylarmt** [comment]
@mdbootstrap Why don't you allow open-source projects, but require a credit in the README or another appropriate place?  Require something like "This project uses mdbootstrap, which you can download at mdbootstrap.com".

FWIW, I don't think you need to worry about uncontrolled redistribution.  It's easier and better to get your code from your website than to get a potentially old version from some random unrelated GitHub project.  I can't think of a single other open-source app that cares at all, and it doesn't affect you anyways, unless you want to track downloads really precisely or something.
