### ISSUE TITLE
Double Navigation with hidden SideNav & (non) fixed Navbar example doesn't work

### ISSUE THREAD

**Issue by DeluxZ** [mdbootstrap/bootstrap-material-design#131]
Both example of the double navigation with hidden sidenav doesn't work. The sidenav isn't hidden when loading the page. 

I can make it hide when I change the source code of 
```
<div id="slide-out" class="side-nav sn-bg-4 fixed mdb-sidenav" style="transform: translateX(0px);">
```
to
```
<div id="slide-out" class="side-nav sn-bg-4 fixed mdb-sidenav" style="transform: translateX(-100%);">
```

https://mdbootstrap.com/previews/docs/latest/html/navigation/side-nav-hidden-navbar-noFixed.html
https://mdbootstrap.com/previews/docs/latest/html/navigation/side-nav-hidden-navbar-fixed.html

**Comment by smolenski-mikolaj** [comment]
Double navigation is working correctly in those links. Please write which browser and OS are You using. SideNav should be visible in default only in wide resolutions.

**Comment by DeluxZ** [comment]
Resolution : 1920x1080
OS: Windows 10
Browser: Firefox 57.0.4 (64-bit)

This is how both examples look like when I load the page.
![1](https://user-images.githubusercontent.com/540033/34867014-d9566bb4-f77e-11e7-80ea-e82fdb628e8b.PNG)
![2](https://user-images.githubusercontent.com/540033/34867015-d96e97fc-f77e-11e7-8858-14983fc27b44.PNG)

**Comment by smolenski-mikolaj** [comment]
So everything is correct. As I said in this resolution sidenav is activated in default.

**Comment by DeluxZ** [comment]
Is it correct that I can't hide the sidenav because part of the content is behind the menu? I think that's pretty weird.

**Comment by smolenski-mikolaj** [comment]
It should be visible, but You're right that it should not cover the menu and rest of the page. We'll try to fix it as soon as possible. Sorry for the misunderstanding.

**Comment by DeluxZ** [comment]
@mattonit why did you close this issue ? Is this fixed ?

**Comment by cccabdalla** [comment]
@DeluxZ , @smolenski-mikolaj , could you please help me a link for downloading the whole project since it is working U on windows 10?
