### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by cjmaxik** [mdbootstrap/bootstrap-material-design#133]
`mdbootstrap` npm package is still on `4.4.4`
![image](https://user-images.githubusercontent.com/1501705/35223634-d1ba1eda-ffcd-11e7-9746-0770bb2c925c.png)

**Comment by rjsworking** [comment]
Hi. I think there's people around like me with a webpack build setup that would benefit from this fix.

Thanks in advance
Cheers

**Comment by rjsworking** [comment]
Done. Thanks.
