### ISSUE TITLE
Multiselect Auto-Scrolls to Selected Option

### ISSUE THREAD

**Issue by jrodl3r** [mdbootstrap/bootstrap-material-design#134]
Each time the user selects an option from a multiselect dropdown list, the list automatically scrolls down to move the newly selected item up to the top of the dropdown ([codepen demo](http://codepen.io/kmmbvnr/pen/wWQwBm)).

This is non-standard UX behavior, and specifically frustrating to our users when a larger dataset is being encompassed (ie: the user is trying to select a large number of non-consecutively placed options).

We would like to see this behavior removed, or at a minimum provide an options to disable this auto-scrolling behavior. We have found a solution that suggests removing a line of the code, however we would very strongly like to avoid any in-house modifications of the MDB assets.

Thanks!

**Comment by JStrebeyko** [comment]
Thanks for letting us know. In the upcoming major MDB update this will cease to be the default behavior. For anyone still wondering, you can fix this behavior by removing/commenting out `line 300: options.scrollTo(option)` of the `material-select.js` file.
