### ISSUE TITLE
Help text on inputs with icons not lining up correctly

### ISSUE THREAD

**Issue by chimericdream** [mdbootstrap/bootstrap-material-design#138]
When using vanilla Bootstrap's `.form-text` class for help text on a form input, the text doesn't line up correctly with the other elements if you also use an icon `.prefix`. See screenshot below.

![screen shot 2018-02-12 at 1 11 34 pm](https://user-images.githubusercontent.com/198075/36114661-472dafb4-0ff6-11e8-8348-fee29896bd18.png)

I have a fix locally and will submit a pull request shortly.

**Comment by Martussky** [comment]
Thank you for your solution. You also can add bootstrap classes, eg. `ml-4 pl-3` to `.form-text` to achieve the same effect.

**Comment by chimericdream** [comment]
True. I knew that I could add the extra classes, but felt this was the more correct solution since the text should always line up automatically, just like the rest of the elements related to the input do.

**Comment by Martussky** [comment]
Thanks for the opinion, we will think.

**Comment by mattonit** [comment]
What's your version of MDB? Could you please re-check it with 4.5.0?

**Comment by chimericdream** [comment]
Just confirmed that the issue is still present in 4.5.0

**Comment by Martussky** [comment]
For now, you can add margin through classes like ml-3, but in next release of MDB, we will add default margins to `help-text` in our SCSS.
