### ISSUE TITLE
Bug: Multiple select not selecting/deselecting options correctly

### ISSUE THREAD

**Issue by fahad-larasoft** [mdbootstrap/bootstrap-material-design#141]
Hi team, 
I am using MDB Pro assets and noticed an issue with Multiple select. It seems to be selecting/deselecting incorrect options. 

For example, it always ignores the last option selected in dropdown and displays all except last one in preview. Let me know if it's an issue on your end or if I need to configure it correctly.

I've configured the mutiselect as follows:

In HTML:
```
<select class="mdb-select" multiple>
    <option value="" disabled selected>Choose your option</option>
    <option value="1">Option 1</option>
    <option value="2">Option 2</option>
    <option value="3">Option 3</option>
</select>
<label>Example label</label>
```

In my js:
    $('.mdb-select').material_select();

Many Thanks,
Fahad Ali

**Comment by JStrebeyko** [comment]
Hi there Fahad,

What version of MDB are you using? Let us know, whether you updated to the lasted one, as it offered some fixes for material select.

Best Regards,
Kuba

**Comment by mattonit** [comment]
closed due to no response

**Comment by denniskuligin** [comment]
Need to open it because I have the same exact problem. I am up-to-date right now. And using pro version.
