### ISSUE TITLE
nav dropdown sample does not match the code

### ISSUE THREAD

**Issue by Peperud** [mdbootstrap/bootstrap-material-design#142]
Straight copy/paste from https://mdbootstrap.com/angular/components/navbars/ results in 

![image](https://user-images.githubusercontent.com/12447865/36284459-945604cc-125c-11e8-82cd-6d3c956af3c1.png)

![image](https://user-images.githubusercontent.com/12447865/36284659-5c21a100-125d-11e8-962d-e7f785c0c504.png)

instead of 
![image](https://user-images.githubusercontent.com/12447865/36284507-b5af3fbc-125c-11e8-9685-29d095017846.png)

![image](https://user-images.githubusercontent.com/12447865/36284667-67414d10-125d-11e8-95f3-23a0ed7d839f.png)

Am I missing anything? There's no point of having sample code if it doesn't match the sample.

**Comment by Bloodcast69** [comment]
Hello Peperud,
This problem was fixed few updates ago in MDB Angular. Which version of MDB do you have? Please update to latest 5.2.0.
Best Regards,
Damian

**Comment by mattonit** [comment]
what's your version of MDB?

**Comment by mattonit** [comment]
closed due to no response
