### ISSUE TITLE
Merge Conflict Markers in 5.2.1 Release Npm

### ISSUE THREAD

**Issue by jameshmread** [mdbootstrap/bootstrap-material-design#149]
### Expected behavior
Expect angular project to compile with no issues
### Actual behavior
Project does not build and produces this error. Looks like there are merge conflict markers in the file
Fails locally as well as in Travis
ERROR in ./node_modules/angular-bootstrap-md/scss/mdb-free.scss
Module build failed: 
    }
    ^
      Invalid CSS after "    }": expected "}", was "<<<<<<< HEAD"
      in /home/travis/build/jameshmread/ProfessorX-App/node_modules/angular-bootstrap-md/scss/angular/free/_navbar.scss (line 51, column 6)
Error: 
    }
    ^
      Invalid CSS after "    }": expected "}", was "<<<<<<< HEAD"
      in /home/travis/build/jameshmread/ProfessorX-App/node_modules/angular-bootstrap-md/scss/angular/free/_navbar.scss (line 51, column 6)
    at options.error (/home/travis/build/jameshmread/ProfessorX-App/node_modules/node-sass/lib/index.js:291:26)
 @ multi ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss ./node_modules/angular-bootstrap-md/scss/mdb-free.scss ./src/styles.scss
ERROR in ./node_modules/angular-bootstrap-md/scss/mdb-free.scss
Module build failed: ModuleBuildError: Module build failed: 
    }
    ^
      Invalid CSS after "    }": expected "}", was "<<<<<<< HEAD"
      in /home/travis/build/jameshmread/ProfessorX-App/node_modules/angular-bootstrap-md/scss/angular/free/_navbar.scss (line 51, column 6)
    at runLoaders (/home/travis/build/jameshmread/ProfessorX-App/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/travis/build/jameshmread/ProfessorX-App/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/travis/build/jameshmread/ProfessorX-App/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/travis/build/jameshmread/ProfessorX-App/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/travis/build/jameshmread/ProfessorX-App/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/home/travis/build/jameshmread/ProfessorX-App/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/home/travis/build/jameshmread/ProfessorX-App/node_modules/async/dist/async.js:958:16)
    at options.error (/home/travis/build/jameshmread/ProfessorX-App/node_modules/node-sass/lib/index.js:294:32)
 @ ./node_modules/angular-bootstrap-md/scss/mdb-free.scss
 @ multi ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss ./node_modules/angular-bootstrap-md/scss/mdb-free.scss ./src/styles.scss
### Your working environment and MDB version information
Dependencies 

    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular-bootstrap-md": "^5.2.1",
    "chart.js": "^2.7.1",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"

  "devDependencies"

    "@angular/cli": "1.6.5",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "puppeteer": "^1.0.0",
    "ts-mockito": "^2.2.9",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"

### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by Bloodcast69** [comment]
Hello jameshmread,
It's fixed right now, so feel free to update your Angular project.
Best Regards,
Damian
