### ISSUE TITLE
Colors cannot be overriden via SCSS anymore

### ISSUE THREAD

**Issue by manuelkiessling** [mdbootstrap/bootstrap-material-design#150]
### Expected behavior

It should be possible to override MDB color variables in one's own SCSS files.

### Actual behavior

Overriding is not possible

### Your working environment and MDB version information

MDB 4.5.0

### Resources (screenshots, code snippets etc.)

In versions up to and including 4.4.5, it was easily possible to override color values via SCSS, because MDB declared its color variables using `!default`. With 4.5.0, this is no longer the case:

https://github.com/mdbootstrap/bootstrap-material-design/blob/4.5.0/scss/core/_colors.scss#L410-L433

**Comment by Martussky** [comment]
Hi,
we know this issue and it will be fixed in the next release.
Best,
Marta

**Comment by mattonit** [comment]
Fixed ;)
