### ISSUE TITLE
Problems with iphone x side screen debugging

### ISSUE THREAD

**Issue by IronnMan** [mdbootstrap/bootstrap-material-design#151]
link:  https://mdbootstrap.com/previews/docs/latest/html/navigation/intro-transparent.html

### environment and MDB version information

chrome ，MDB 4.5.0

### Resources (screenshots, code snippets etc.)

![2018-03-09 3 16 50](https://user-images.githubusercontent.com/22145534/37195603-88b901ba-23ae-11e8-9751-7f4251a37df8.png)

**Comment by Martussky** [comment]
Hi,
I can't reproduce the problem (I see our live preview works correctly). Please, provide more information, eg. demo, which version of Chrome you use etc.

**Comment by mattonit** [comment]
closed due to no response
