### ISSUE TITLE
pointer cursor when hovering legend on charts

### ISSUE THREAD

**Issue by koop4** [mdbootstrap/bootstrap-material-design#155]
### Expected behavior
When mouse hovering any legend item, i'd expect to see a cursor: pointer

### Actual behavior
When mouse hovering any legend item,  cursor is default

**Comment by Martussky** [comment]
Hi,
we will look at this and probably change in the future.

**Comment by Martussky** [comment]
Hi,
if you want to have a pointer cursor on hover in a chart, add to the "options" the following code:
```
legend: {
            onHover: function(e) {
              e.target.style.cursor = 'pointer';
            }
          },
          hover: {
            onHover: function(e) {
              var point = this.getElementAtEvent(e);
              if (point.length) e.target.style.cursor = 'pointer';
              else e.target.style.cursor = 'default';
            }
          }
```
Best,
Marta
