### ISSUE TITLE
Wrong inclusion of function within mixin

### ISSUE THREAD

**Issue by cjmaxik** [mdbootstrap/bootstrap-material-design#158]
You can't declare functions within mixins - it will throw an error "Functions may not be defined within control directives or other mixins".

https://github.com/sass/sass/issues/2470

https://github.com/mdbootstrap/bootstrap-material-design/blob/40ba6e276de09adcf8ddab56bd4a8cfde97cbf2a/scss/core/_mixins.scss#L215

**Comment by MelonSmasher** [comment]
Also getting this.

**Comment by Martussky** [comment]
Hi,
we know this bug and in our next release, it will be fixed.
Best,
Marta

**Comment by cjmaxik** [comment]
Solved in 4.5.1
