### ISSUE TITLE
Labels do not work as expected with prefilled input controls

### ISSUE THREAD

**Issue by alex94puchades** [mdbootstrap/bootstrap-material-design#16]
Form labels do not detect that the input control has content until it is focused.

**Comment by mdbootstrap** [comment]
try to add a class .active to the label when updating the input value.

Another solution is keeping the label always up. You can do it via sass/css

go to sass/mdb/free/_form-basic.scss and in line 130 remove .active class.

label.active {

change to:

label {

Then compile your custom mdb.css

**Comment by PabloValor** [comment]
I have the same problem, sometimes label text overlap the input value.
Removing the class fix the thing, but I miss that fancy animation :(
