### ISSUE TITLE
4.5.1 is broken (color maps)

### ISSUE THREAD

**Issue by cjmaxik** [mdbootstrap/bootstrap-material-design#161]
### Expected behavior
Completed compiling (like on 4.5.0)

### Actual behavior
```
Argument `$map2` of `map-merge($map1, $map2)` must be a map
in [...]\node_modules\mdbootstrap\scss\core\_colors.scss (line 43, column 7)
```
Because **$red** has been already set in **bootstrap** itself!

### Your working environment and MDB version information
node v8.11.1, npm v5.6.0, yarn v1.5.1, 
**bootstrap v4.1.0, mdbootstrap v4.5.1**

### Resources (screenshots, code snippets etc.)
scss file
```scss
@import "~bootstrap/scss/bootstrap";
@import "~mdbootstrap/scss/mdb";
```

**Comment by cjmaxik** [comment]
@Martussky https://gist.github.com/cjmaxik/b6e20bdc2f9124210bf9658e3aac04ee

**Comment by Martussky** [comment]
In this package we still use Bootstrap 4.0.0 and we don't use all of Bootstrap variables, if you download new MDB Free 4.5.1 package and go to scss/core/bootstrap/variables.scss then you will see that many of bootstrap variables is commented because they conflict with our variables. That's why we've commented them.

**Comment by cjmaxik** [comment]
Run `yarn add bootstrap@4.0.0 && yarn run production` and you will see the same result.

**Comment by Martussky** [comment]
OK, but you have this problem in the newest package where anything won't change? From your statement, it appears that you have overwritten our file with another file.

**Comment by cjmaxik** [comment]
I just want to compile MDBootstrap with Bootstrap from sources for my website. What is your approach to do so? Maybe it was my mistake to grab `bootstrap` then throw `mdbootstrap` on top of it.

**Comment by cjmaxik** [comment]
It starts to sound complicated to compile that mess :) So, what should I do now to compile it?

**Comment by Martussky** [comment]
If you want to have only MDB styles, just do the same what we did - comment or delete that Bootstrap variables which make a conflict. I don't have a better idea, because most of our users just use our scss files and don't import raw bootstrap ones.

**Comment by beany-vu** [comment]
I got the same issue if I use bootstrap version 4.1.0 and mdbootstrap 4.5.1. If I use the older one (bootstrap 4.0.0 and mdbootstrap 4.5.0) then I don't face this problem.
I guess that node-sass hasn't yet adapted to the newer version of these dependencies.

**Comment by Martussky** [comment]
Hi,

we still use Bootstrap 4.0.0 and we will update our package to the new
Bootstrap 4.1.0 in the next release which will be in May.

Kind regards,



Marta Szymanska

+48 728 100 245
www.MDBootstrap.com <http://mdbootstrap.com/material-design-for-bootstrap/>


2018-04-24 7:04 GMT+02:00 Beany Vu <notifications@github.com>:

**Comment by raisonon** [comment]
Trying to add MDB to an existing BS project. 

Get: Error: argument `$map2` of `map-merge($map1, $map2)` must be a map

Which is due to $red -- this is defined in BS Vars. Is this causing the issue?

Any ideas how to resolve? I tried commenting out from BS core, but these vars are used throughout BS.

Thanks

**Comment by Martussky** [comment]
Hi,
this issue with MDB and Bootstrap variables will be solved in the next release, which will be in May. I apologize for the problem. If you use only these bootstrap files which are in our package, not the newest Bootstrap it should be OK. We will update MDB package to the newest Bootstrap 4.1.0 in the next release.
Best,
Marta

**Comment by raisonon** [comment]
Hi Marta, I'm using BS 4.0.0 at the moment and get the issue - is it something else?

**Comment by Martussky** [comment]
Hi,
do you use Bootstrap files from our MDB 4.5.1 package?

**Comment by raisonon** [comment]
No, I don't.

I have an existing project where we have pulled BS using NPM.

Aim at the moment is just use the Material form styling...

Thanks

**Comment by raisonon** [comment]
Error: argument `$map2` of `map-merge($map1, $map2)` must be a map
This is: $red: () !default;

$red: () !default;
$red: map-merge((
  "lighten-5":  $red-lighten-5,
  "lighten-4":  $red-lighten-4,
  "lighten-3":  $red-lighten-3,
  "lighten-2":  $red-lighten-2,
  "lighten-1":  $red-lighten-1,
  "base":       $red-base,
  "darken-1":   $red-darken-1,
  "darken-2":   $red-darken-2,
  "darken-3":   $red-darken-3,
  "darken-4":   $red-darken-4,
  "accent-1":   $red-accent-1,
  "accent-2":   $red-accent-2,
  "accent-3":   $red-accent-3,
  "accent-4":   $red-accent-4
), $red);

**Comment by Martussky** [comment]
For this package - MDB 4.5.1 we commented some of Bootstrap variables in our core/bootstrap/variables.scss file, because they had conflict with our variables, that's why any new file, not ours will have conflict. This problem will be fixed in the next release which will be in May 7th.

**Comment by Martussky** [comment]
You're welcome.

**Comment by cjmaxik** [comment]
4.5.2 release has resolved the issue. Closing.

**Comment by JihedHalimi** [comment]
We have the exact same problem with angular-bootstrap-md 6.0.2

**Comment by Martussky** [comment]
It should be fixed in the next MDB Angular release.

**Comment by pixelfriese** [comment]
So, I have found a quick fix for that, but it is not very clean in my eyes:

https://mdbootstrap.com/support/possible-problem-in-mdb-4-5-1/

I have created a new Sass file like in Josip Tomašev´s answer an put it between the Sass file of bootstrap and MDB:

```
$white: ();
$black: ();

$blue: ();
$indigo: ();
$purple: ();
$pink: ();
$red: ();
$orange: ();
$yellow: ();
$green: ();
$teal: ();
$cyan: ();

$colors: ();
```

**Comment by cjmaxik** [comment]
@pixelfriese did you **really sure** that you're using mdb v4.5.2?

**Comment by Martussky** [comment]
Hi,
I don't know why in your MDB 4.5.2 package you still had issues, but for sure since that version, the compiling errors have been corrected. Please provide more details if you still need help.
Best,
Marta

**Comment by abhijitgujar86** [comment]
in 4.7.6 I still have the same issue

**Comment by Martussky** [comment]
Hi,

in our newest package 4.10.1, there shouldn't be a problem.

Best, Marta
