### ISSUE TITLE
Dropdown in navbar wrong text color on hover

### ISSUE THREAD

**Issue by elbojoloco** [mdbootstrap/bootstrap-material-design#162]
### Expected behavior
Either text stays dark with light background, or background turns dark and text turns light.

### Actual behavior
Non-hover is light bg with dark text, hover is light bg with light text.

### Your working environment and MDB version information
jQuery 3.3.1, Bootstrap 4.0.0, MDB 4.4.5

### Resources (screenshots, code snippets etc.)
![wrongoclor](https://user-images.githubusercontent.com/7912315/38983642-18c44798-43c5-11e8-9243-a29f05477340.gif)

**Comment by Martussky** [comment]
It was fixed in 4.5.0 version. I recommend you to update your package to the newest version of MDB - 4.5.1.

**Comment by elbojoloco** [comment]
Ah okay, thanks!
