### ISSUE TITLE
Waves cannot be initialised due to document.body not being available 

### ISSUE THREAD

**Issue by nKittie** [mdbootstrap/bootstrap-material-design#165]
### Expected behavior
Wave.init not to throw an exception

### Actual behavior
With mdb.js script in the HEAD part of the page, Waves.init fails on the line: body.addEventListener('mousedown', showEffect, false);
due to document.body = null. At this point document object exists and has head but no body.
Moving <script src=mdb.js... line to after the body in DOM makes this work fine.

### Your working environment and MDB version information
HTML5, Windows 10, Chrome 66, MDB free version

### Resources (screenshots, code snippets etc.)
![image](https://user-images.githubusercontent.com/2365410/39622815-6affc7fe-4f8b-11e8-912d-5f43feadc8ed.png)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by cjmaxik** [comment]
Actually, why do you need the scripts in the HEAD?

**Comment by nKittie** [comment]
Fair enough, didn't see that requirement!
