### ISSUE TITLE
Error and success input labels position and size

### ISSUE THREAD

**Issue by pixelfriese** [mdbootstrap/bootstrap-material-design#168]
Hi,

### Expected behavior
Position of the error and success labels should be directly under the input line. The font-size should be smaller than the input label size.

### Actual behavior
If I have an empty input field with an input error/success label, the font size is the same as the font-size of the input and the position and size of the label is too small and lies under the next input field. 

### Your working environment and MDB version information
4.5.3 Pro Version jQuery

### Resources (screenshots, code snippets etc.)
![issue1](https://user-images.githubusercontent.com/13178131/40558895-152dd1ba-6055-11e8-8363-3fd4b3b4ca29.jpg)

![issue2](https://user-images.githubusercontent.com/13178131/40558896-15485d28-6055-11e8-9d5e-984ecd3d4d38.jpg)

**Comment by Martussky** [comment]
Hi,
thank you for report this issue. We will fix this as soon as possible and we will inform about it in our [changelog](https://mdbootstrap.com/changelog/). Sorry for the problems.
Best,
Marta

**Comment by Martussky** [comment]
Hi,
this is already fixed.
Best,
Marta
