### ISSUE TITLE
Disable js waves effect on specific links (nav)

### ISSUE THREAD

**Issue by raisonon** [mdbootstrap/bootstrap-material-design#170]
### Expected behavior
Added MDB to package and now get waves onclick effect on my navigation which creates a background color I do not want. I want no effect. Ideally I want to remove the waves classes from the navigation.

### Actual behavior
waves classes are added to the navigation and there is the styling issue on the navigation.

### Your working environment and MDB version information
Custom build with JS and relevant SCSS added to theme.

**Comment by raisonon** [comment]
Waves.destroy has been added to version 0.8 of Waves. Outlined here:  https://github.com/fians/Waves/issues/159

I can see that MDB is using Waves v0.7.5 

Can this be updated this so we can destroy this effect without having to comment out the waves.attach lines.

Thanks

**Comment by raisonon** [comment]
Fantastic, that would be great as at the moment having waves at 0.75 makes it unusable for us :( Will have to edit the core code. Appreciate the update

**Comment by JStrebeyko** [comment]
It should  be a part of the next (not the nearest-upcoming, but next) agenda. Thanks! Closing

**Comment by pglejzer** [comment]
I close this issue because https://github.com/fians/Waves/releases there is no v0.8.0 released and we can't update this package.
