### ISSUE TITLE
For input type != text, required not working

### ISSUE THREAD

**Issue by s1lviu** [mdbootstrap/bootstrap-material-design#171]
### Expected behavior
Required field
### Actual behavior
Form submits without having field as required
### Your working environment and MDB version information
MDB PRO 4.4.3
### Resources (screenshots, code snippets etc.)
```
<input name="email" id="userEmail" type="email" required="required" autocomplete="email"
                                       class="form-control validate">
```
The presented snippet don't make the field required. If I change the input type with `text` instead of `email` will work.

**Comment by anna-morawska** [comment]
Hi there, 
it's already fixed in the recent version.
