### ISSUE TITLE
scss/mdb.scss in MBD 4.5.7 is a Pro version

### ISSUE THREAD

**Issue by jfcherng** [mdbootstrap/bootstrap-material-design#173]
Cannot build with Webpack for MDB free.

`scss/mdb.scss` is somehow become a Pro version 4.5.7.

https://github.com/mdbootstrap/bootstrap-material-design/blob/af3377a9d168a49b60c4858051844ad59d5af088/scss/mdb.scss#L3

The following scss files are missing in this Free repo.

https://github.com/mdbootstrap/bootstrap-material-design/blob/af3377a9d168a49b60c4858051844ad59d5af088/scss/mdb.scss#L68-L118

**Comment by DroneZzZko** [comment]
**EPIC FAIL** 
Why is it still **OPEN**?

**Comment by jfcherng** [comment]
fixed in 4.5.8.
