### ISSUE TITLE
Unwanted Pro version imports in mdb.scss that creates problem while compiling assets with laravel mix.

### ISSUE THREAD

**Issue by iyashpal** [mdbootstrap/bootstrap-material-design#174]
### Expected behavior
There must be no pro imports in mdb.scss as this is a free version. 

### Actual behavior
unnecessary imports in mdb.scss creates problem while compiling with webpack.mix in Laravel. To resolve the issue I always need to remove these imports from mdb.scss file. Please remove these unnecessary imports from free version of mdbootstrap

### Your working environment and MDB version information
mdb free via npm package.

### Resources (screenshots, code snippets etc.)
Screenshot: http://prntscr.com/k9k0yj

Thank you very much for providing us free version of mdbootstrap.

**Comment by mattonit** [comment]
this was fixed already
