### ISSUE TITLE
Separate generated code and variables

### ISSUE THREAD

**Issue by JoniJnm** [mdbootstrap/bootstrap-material-design#175]
### Expected behavior

Include variables (colors.scss) and don't generate css code

### Actual behavior

When I include mdb variables, colors.scss generates css code

### Your working environment and MDB version information

Free 4.5.7

### Resources (screenshots, code snippets etc.)

I think that the files that define variables should not generate css code. For example I need to include bootstrap and mbd variables:

```
@import ".../core/bootstrap/functions";
@import ".../core/bootstrap/variables";
@import ".../core/mixins";
@import ".../core/colors";
@import ".../core/variables";
```

But colors.scss generates css code

```
@each $color_name, $color in $material-colors {
  .#{$color_name} {
    background-color: $color !important;
  }
}
```

Can you move this to another file? Maybe to global.scss

**Comment by mdbootstrap** [comment]
Hi,
we will think about a better solution for colors, thank you.
Best,
Marta

**Comment by JoniJnm** [comment]
It's done but still exists:

https://github.com/mdbootstrap/bootstrap-material-design/blob/master/scss/core/_colors.scss#L614-L620

You have to move it to global.scss

**Comment by Martussky** [comment]
Hi,
we will.
Best,
Marta
