### ISSUE TITLE
nav-link in nav-tabs is broken in default bootstrap behavior

### ISSUE THREAD

**Issue by g-p-n** [mdbootstrap/bootstrap-material-design#176]
### Expected behavior
nav-link in default Bootstrap nav-tabs is broken
### Actual behavior
I believe, this code segment in scss/free/_modals.scss:267 breaks the nav-link appearance in default bootstrap.

```
.nav-tabs {
  border-radius: $md-card-border-radius;
  .nav-item {
    .nav-link {
      border-radius: $md-card-border-radius;
      background-color: inherit;
      color: $white-base;
    }
  }
}

```
### Your working environment and MDB version information
Free 4.5.7.

### Resources (screenshots, code snippets etc.)
I build using gulp, and here is the gulp task I am currently using to workaround this behavior.

```
gulp.task("mdbootstrap-modify", function() {
  gulp.src(["node_modules/mdbootstrap/scss/free/_modals.scss"])
      .pipe(gulp_replace(/^\.nav-tabs/gm, "\.nav-tabs-rule-removed"))
      .pipe(gulp.dest("./node_modules/mdbootstrap/scss/free/"));
});

```
- Is the code segment intended?
- Is there any other better/cleaner workaround than what I have suggested?

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by gitBC** [comment]
I'm also having this problem. Looks like the problem was introduced here: https://github.com/mdbootstrap/bootstrap-material-design/commit/9b4ffd1df9b9ab3335b5324a090ecda64bcbcc81

I've created a patch to correct the issue which moves the .nav-tabs class within the .modal class

**Comment by mdbootstrap** [comment]
Hi,
we will fix that bug as soon as possible and we will inform you after that.
Best,
Marta

**Comment by Martussky** [comment]
Hi,
please, update your MDB package, we've fixed this already.
Best,
Marta
