### ISSUE TITLE
Directory path for arrows pushed one down since version 4.5.6, but why? 

### ISSUE THREAD

**Issue by Folatt** [mdbootstrap/bootstrap-material-design#179]
### Expected behavior
No errors.

### Actual behavior
Blank screen with two errors about missing arrows. Left and right.

### Your working environment and MDB version information
- Arch Linux
- MDB version 4.5.6 and up.

### Resources (screenshots, code snippets etc.)

```
ERROR in ./node_modules/css-loader??ref--2-1!./node_modules/mdbootstrap/css/mdb.css
Module not found: Error: Can't resolve '../../img//svg/arrow_left.svg' in '/home/folatt/Cloud/workspace/atom/Sites/Yropeên/node_modules/mdbootstrap/css'
 @ ./node_modules/css-loader??ref--2-1!./node_modules/mdbootstrap/css/mdb.css 7:240646-240686
 @ ./node_modules/mdbootstrap/css/mdb.css
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:5000 (webpack)/hot/dev-server.js ./src/index
```

**Comment by pglejzer** [comment]
Hi,
my name is Piotr and I'm from MDB staff. Can you check this fix?
You have to go to your _variables.scss at pro folder.
And change 

$pswp__button-background:                url(#{$image-path1}/lightbox/default-skin.png) !default;
$pswp__button-background-image:          url(#{$image-path1}/lightbox/default-skin.svg) !default;
$pswp__preloader__icn-background:        url(#{$image-path1}/lightbox/preloader.gif) !default;

Best,
Piotr

**Comment by Folatt** [comment]
There are two _variables.scss files, one in core and one in core/bootstrap and neither of them I kind find similar lines like yours.

Best,
Folatt

**Comment by Martussky** [comment]
Hi,
we've fixed this issue and it will be contained in our package after release which will be 14.08.
Best,
Marta
