### ISSUE TITLE
Integrate with Bootstrap Kit

### ISSUE THREAD

**Issue by tonystar** [mdbootstrap/bootstrap-material-design#18]
How about to share some base code with Bootstrap Kit?
Some components could be useful for generic Bootstrap and vice versa!

https://github.com/highweb/bootstrap-kit

**Comment by mdbootstrap** [comment]
Thank you for idea. We'll take a look at it.

Best,

Michal Szymanski

+48 604 956 280
www.MDBootstrap.com <http://mdbootstrap.com/material-design-for-bootstrap/>

<https://www.linkedin.com/pub/michal-szymanski/8a/891/922>
<https://twitter.com/MDBootstrap>
<https://plus.google.com/+Micha%C5%82Szyma%C5%84skiBF/posts>
