### ISSUE TITLE
Modal window long select.

### ISSUE THREAD

**Issue by GoochWeb** [mdbootstrap/bootstrap-material-design#180]
### Expected behavior
Closing the selector after selecting a specific option.

### Actual behavior
The selector does not close when an option is selected.

### Your working environment and MDB version information
Free 4.5.7.

### Resources (screenshots, code snippets etc.)
Code:
https://pastebin.com/EmTeHEdZ

**Comment by JStrebeyko** [comment]
Hi there,

This and some other reasons made us rewrite the select from scratch. It should be out at the beginning of next week, so keep your eyes peeled.

Best, Kuba

**Comment by GoochWeb** [comment]
How can I now change that it works, maybe there is some crutch

**Comment by GoochWeb** [comment]
This temporary solution closes and multi select, how to fix code, so that this does not happen

**Comment by catchmareck** [comment]
Yo uhave to modify the selector to something like this:

`$(".mdb-select:not([multiple])")`
