### ISSUE TITLE
Can't visit MDBootStrap site after raised a Support Issue

### ISSUE THREAD

**Issue by Mikuu** [mdbootstrap/bootstrap-material-design#181]
Hi,

This is very strange, after I raised a Support issue in mdbootstrap site, I can't open the whole site at all at [https://mdbootstrap.com/](https://mdbootstrap.com/.)

What's that issue?

**Comment by mattonit** [comment]
@Mikuu,

Recently, we're facing a lot of spam on our website so we've made our security systems stronger. It looks like your IP address was blocked too. Please contact us at support@mdbootstrap.com and provide your IP address (you can check it here: http://whatsmyip.org). After you send us your IP, we'll unblock your access to mdbootstrap.com

**Comment by shajeelawrence2709** [comment]
This is unfortunate.  I have provided my IP address - even then not able to access the site. What's the issue?

**Comment by mattonit** [comment]
@shajeelawrence2709 I can confirm I received an e-mail from you. Your IP is now unblocked

**Comment by shajeelawrence2709** [comment]
Thank you so much - much appreciate your help.

Best,
Shajee
