### ISSUE TITLE
4.5.9 Material Select causes catastrophic crash during destroy + rebuild

### ISSUE THREAD

**Issue by kearns-arthur** [mdbootstrap/bootstrap-material-design#183]
### Expected behavior
Destroying and rebuilding of a material select list correctly.

### Actual behavior
Hangs or crashes the browser.

### Your working environment and MDB version information
MDB PRO 4.5.9, Windows, any browser

### Resources (screenshots, code snippets etc.)
In 4.5.8 this was not an issue.  In 4.5.9 there is a new '_onMutationObserverChange' and it is my assumption this new function is the problem.

![458](https://user-images.githubusercontent.com/23104205/45060136-4e334080-b064-11e8-9086-942466b498e9.png)
Version 4.5.8 Performance

![459](https://user-images.githubusercontent.com/23104205/45060156-61dea700-b064-11e8-8f6c-98dffe8a2c69.png)
Version 4.5.9 Performance

My script:
`        function getMakesModels(id) {
            $.ajax({
                type: 'GET',
                url: uri + "/getmakemodels/" + id,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    document.getElementById('idxmodels').options.length = 0;
                    $('#idxmodels').append(`<option value="" disabled selected>Choose a Model</option>`);
                    $.each(data,
                        function (i, item) {
                            $('#idxmodels').append(`<option value="">${item}</option>`);
                        });
                    $('.mdb-select').material_select('destroy');
                    $('.mdb-select').material_select();
                },
                failure: function (response) {
                    alert(response.d);
                },
                error: function (response) {
                    alert(response.d);
                }
            });
        }`

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by catchmareck** [comment]
Hi, indeed there is a nasty bug in our code. It's caused by MutationObservers which are not disconnected on the Material Select re-render. It has been fixed already and will be available in the nearest release. For now, you just need to get rid of the mentioned method and manually rebuild/re-minify the package. Sorry for inconveniences

**Comment by vladviolenty** [comment]
i see problem with perfomance 
$('.mdb-select').materialSelect({destroy: true});
                        $("select#selectMultiReserve").html("");
                        rsp.forEach(function (el) {
                            $("select#selectMultiReserve").append("<option value='"+el['id']+"'>"+el['city']+". с "+el['start']+". по "+el['stop']+"</option>");
                        });
                        $('.mdb-select').materialSelect();

**Comment by vladviolenty** [comment]
I see like problem in MDB 4.8.4
![Screenshot_20191111_153426](https://user-images.githubusercontent.com/10224008/68587721-c8492b80-0498-11ea-846e-40a499b9fbb1.png)
