### ISSUE TITLE
Incorrect work after redefining SCSS $warning-color variable

### ISSUE THREAD

**Issue by burdukowsky** [mdbootstrap/bootstrap-material-design#187]
### Expected behavior
After redefining `$warning-color` SCSS variable CSS-class `text-warning` should use 'warning' color. Instead this `text-warning` class using 'warning-dark' color. With other colors (primary, secondary, info, success, danger) all right.
### Actual behavior
After redefining `$warning-color` SCSS variable CSS-class `text-warning` using 'warning-dark' color.
### MDB version information
mdbootstrap v4.5.10
bootstrap v4.1.3
### Repo with demonstration
https://github.com/burdukowsky/mdbootstrap-test

--
Sorry for my English.

**Comment by mdbootstrap** [comment]
Hi,
Thank you for noticing this. We will check it and fix in another release.
Best,
Marta

**Comment by Martussky** [comment]
Hi,
Thank you for noticing this. We will check it and fix in another release.
Best,
Marta

**Comment by burdukowsky** [comment]
Fixed in version 4.5.16.
