### ISSUE TITLE
IE 11 not working anymore starting MDB 4.5.10

### ISSUE THREAD

**Issue by icebits** [mdbootstrap/bootstrap-material-design#188]
### Expected behavior
mdb.js should work (no script error) on IE 11.

### Actual behavior
IE 11 throw script error

### Your working environment and MDB version information
Microsoft MVC 5, Bootstrap 4.1.3, MDB 4.5.10

It seem new written pattern/syntax which didn't recognize by IE 11, is it ES6?  I switch back 4.5.9 no issue at all.

It failed on this pattern:
($ =>{ 
 const i = 1;
})(jQuery);

this pattern ok:
(function ($) {
 var i = 1;
})(jQuery);

**Comment by Martussky** [comment]
Hi,

as you can read in our official statement of supported browsers and devices, we do not support IE.

[Link about IE](https://mdbootstrap.com/browsers-and-devices/)

That means, most of the things will work, but some of them will not (like components based on flexbox etc.). That's nothing we can do about it because IE is so outdated.

There is no ETA for this bug. We'are sorry, but we have much more important things to deliver than support for old, outdated browser which is hardly used by anyone.

Best,
Marta

**Comment by jfcherng** [comment]
https://github.com/jfcherng/my-mdbootstrap

I have a [transpiled jQuery version of 4.5.10](https://github.com/jfcherng/my-mdbootstrap/releases/download/4.5.10/mdbootstrap-4.5.10.zip). But it has more custom CSS fixes than that for me. If may you only need to take `mdb.min.js`.

You may have to use https://cdnjs.com/libraries/babel-polyfill as well if `mdb.min.js` uses non-ES5-compatible natives. I am not sure.

**Comment by mdbootstrap** [comment]
@Diazole-x , 
My apologies for your inconvenience. 

IE11 was released on 29 July 2015 which means it's already 4 years old. We are trying to support as many features as possible with backward compatibility, however sometimes we have to drop compatibility for outdated products in favour of new features which let MDB bring new outstanding functionality.  I hope you can understand that. 

There is no option to have both, therefore please use the legacy version of MDB which were compatible with IE, or, if possible - switch to the newer version of the browser (Edge, Chrome etc).

**Comment by icebits** [comment]
Hi. I understand that IE11 is less favorable now but it is hard in enterprise environment :(. I suggest to update Github readme to remove IE from compatible wording as it might misleading to other users or indicate that IE support is until 4.5.9 only.

Cross-browser compatibility
Chrome, Firefox, IE, Safari, Opera, Microsoft Edge - MDB loves all browsers, all browsers love MDB.
