### ISSUE TITLE
Window.Waves is undefined when MDB Free is used into the NWJS.io

### ISSUE THREAD

**Issue by edelciomolina** [mdbootstrap/bootstrap-material-design#19]
I´m using NWJS.io to create a app with MDB. But, the Waves.js (inside into mdb.js) can´t loaded. I tried to run the code of Waves.js into console of NWJS but "Window.Waves" is shown always as 'undefined'.
In the fist time that I opened the index.html inside 'MDB Free' a exceptions happens:

![image](https://cloud.githubusercontent.com/assets/4604923/19483838/7bff7dc8-9534-11e6-8fe8-19c0472a76c9.png)
NOTE: I tried into Chrome Browser and there works fine!

**Comment by mattonit** [comment]
We'll take a look at this with the new release. Thanks for PR
