### ISSUE TITLE
Input validation not working

### ISSUE THREAD

**Issue by SerhiDi** [mdbootstrap/bootstrap-material-design#190]
### 'data-success' and 'data-error' messages not working with mdbInputDirective

In my project I used version "**angular-bootstrap-md": "6.2.4**".
span tags '_inputVal text-success_' & '_inputVal text-danger_' - are always ignoring any validation, '_visibility: hidden;_' in any time.

I used the example code (Error or Success Messages):
[Inputs](https://mdbootstrap.com/angular/forms/inputs/)
```
<div class="md-form">
  <i class="fa fa-envelope prefix"></i>
  <input mdbInputDirective data-error="wrong email" [formControl]="emailFormEx" data-success="valid email" minLength="8" maxLength="25"
        type="email" class="form-control" id="form9" name="email" mdbInputDirective>
  <label for="form9">Type your e-mail</label>
</div>
```

### (additional bug) mdbInputDirective - two times in your example
---
You have an incorrect documentation on examples page:
[Input validations](https://mdbootstrap.com/angular/forms/input-validation/)

Each validators are show wrong messages
For example '**minLength validator**' - show "_wrong_" insted "_wrong text_".

**Comment by idzark** [comment]
Thank you for letting us know about these problems. We will update examples in our documentation.

Please try to use the code from the [Input validation](https://mdbootstrap.com/docs/angular/forms/validation/) page and let me know if the problem with displaying validation messages still exists (please remember to import ReactiveFormsModule).
