### ISSUE TITLE
Bootstrap Differences

### ISSUE THREAD

**Issue by isabasan** [mdbootstrap/bootstrap-material-design#194]
I installed mdb and bootstrap via npm. There are too many differences between the original dist of bootstrap.min.css and node_modules/mdbootstrap/css/bootstrap.min.css

### Expected behavior
node_modules\bootstrap\dist\css\bootstrap.min.css and node_modules\mdbootstrap\css\bootstrap.min.css must be same.

### Actual behavior
There are too many diff between bootstrap.min.css files.

### Your working environment and MDB version information
node -v : v11.0.0
npm -v: 6.4.1
mdbootstrap : 4.5.13
### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by Martussky** [comment]
Hi,
thank you for noticing this issue, for sure we will check it and change bootstrap file in our package in the next release.
Best,
Marta

**Comment by pglejzer** [comment]
Hi, 
we already fix that issue. Have a nice day.
Best, 
Piotr
