### ISSUE TITLE
Smooth scrolling does not work on free version

### ISSUE THREAD

**Issue by isabasan** [mdbootstrap/bootstrap-material-design#195]
There is no MDB Pro Badge on this component page. (https://mdbootstrap.com/javascript/smooth-scroll/). But it looks like, required js is not in free version. I am not sure if it is a bug of free version or missing information about pro version ?

### Expected behavior
Smooth scrolling
### Actual behavior
Scrolling is not smooth
### Your working environment and MDB version information
MDB 4.5.13
### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by pglejzer** [comment]
Yes, that was a little bug. We added MDB PRO Badge to show which component is pro. Thank you very much for your post. :trophy:  Have a nice day.
