### ISSUE TITLE
non css entity causing css-minify to render broken mdb.min.css 

### ISSUE THREAD

**Issue by ako80218** [mdbootstrap/bootstrap-material-design#197]
### Expected behavior
After running `gulp css-minify` mdb.min.css lines 1 - 2 should look like this:
```
/*!
 * Material Design for Bootstrap 4
```

### Actual behavior
After running `gulp css-minify` mdb.min.css lines 1 - 2 look like this:
```
@charset "UTF-8";/*!
 * Material Design for Bootstrap 4
```

Basically mdb.min.css is broken yielding faulty css.

### Your working environment and MDB version information
I am running mdb gulp tasks on a Mac , High Sierra Version 10.13.6. I am working with MDB PRO 4.5.14

### Resources (screenshots, code snippets etc.)
I think the problem is a non css entity in /dist/css/addons-pro/_cards-extended.scss  on line 31.

Line 31 is currently:
`content: "˚C";`

I think line 31 should be:
`content: "\00b0 C";`

I'll change the code and issue a pull request if possible.

**Comment by mattonit** [comment]
Thank you for letting us know! We'll definitely fix that in the nearest release. In fact, to submit a PR, you need to get an access to our GitLab repository. If you're already a pro user, you should have it already. If you don't have an access to our jq-pro repository, you can catch me at b.malanowski@mdbootstrap.com

**Comment by ako80218** [comment]
Thanks @mattonit. I have emailed you.
