### ISSUE TITLE
Cards not behaves like original card in Bootstrap 4 - img issue

### ISSUE THREAD

**Issue by rafalradomski** [mdbootstrap/bootstrap-material-design#2]
When I add picture with different sizes to card I expect that image will automatically be extended to whole space in img box and the cards will have the same height always.

[Cards in Bootstrap 4 Alpha](http://v4-alpha.getbootstrap.com/components/card/#decks)

![https://s4.postimg.io/bguhwks8d/bootstrap.png](https://s4.postimg.io/bguhwks8d/bootstrap.png)

How it works in MDB right now:

![https://s4.postimg.io/9qbgv3ap9/mdb.png](https://s4.postimg.io/9qbgv3ap9/mdb.png)

**Comment by mdbootstrap** [comment]
3 weeks ago Bootstrap team released alpha-3 for Bootstrap 4 (which makes improvements for flex box, indeed). 

MDB is built with alpha-2 and we are currently working on update. Next week we'll release a new version updated to Bootstrap 4 alpha-3 and problem will be solved.

**Comment by rafalradomski** [comment]
Yes default behavior is like you described, but Bootstrap 4 offers as well option to [group elements](http://v4-alpha.getbootstrap.com/components/card/#groups): and images have the same size. 

Are you planing to implement that functionality?

**Comment by mdbootstrap** [comment]
In the upcoming update we'll enable all available in Bootstrap 4 alpha-3 options.
