### ISSUE TITLE
MDBootstrap modal issues.

### ISSUE THREAD

**Issue by DoubleThePsycho** [mdbootstrap/bootstrap-material-design#201]
### Expected behavior
Modals were expected to load properly, stick to the top of and follow the screen as shown on the [example site](https://mdbootstrap.com/docs/jquery/modals/basic/).

### Actual behavior
Modals open, but are not following the screen.
They open at a specific location on the screen and will stay there.
The modal backdrop is loaded **above** the modals, preventing the viewer from closing the modal.
[Video](https://img.doublethepsycho.site/m/MDBootstrap-modal-issue). (Mind your volume.)

### Your working environment and MDB version information
PHP version 7.2, live web server.
All resources needed by MDBootstrap are updated as shown on the getting started page.

### Resources (screenshots, code snippets etc.)
[Screenshot](https://img.doublethepsycho.site/l8fie).

**Comment by DoubleThePsycho** [comment]
Hello,

My mistake, an update was released just recently, and I was not completely up to date.
I updated to the latest CDN links and all worked flawlessly.
In other words, issue resolved.

While the ticket is still active, a new issue has occurred since I updated.
Pills no longer work, and take you to `domain.com#pill-id` rather than switching tab.
I copied the demo code from your pills introduction, and they don't work either.

Regards,
- Stefan DoubleThePsycho

**Comment by Martussky** [comment]
Hi,
I've tried to open your website to look at the problem but I have a message "This site can’t be reached". Please, recreate the problem by creating the snippet here: [https://mdbootstrap.com/snippets/](https://mdbootstrap.com/snippets/). I'll try to help you.
Best,
Marta

**Comment by DoubleThePsycho** [comment]
Hello,

The domain got updated to https://doublethepsycho.com just recently.

Regards,
- Stefan DoubleThePsycho

**Comment by pglejzer** [comment]
Thanks for the advice. We will know about that. Have a nice day.
