### ISSUE TITLE
No option to change default link hover color. Proposing $link-hover-color to be used in _global.scss

### ISSUE THREAD

**Issue by MichaelHabib** [mdbootstrap/bootstrap-material-design#202]
### Expected behavior
Expecting an option to change the default link hover color from the bootstrap default (blue) to a user defined color.
### Actual behavior
There is no variable to change the default link hover color.
### Your working environment and MDB version information
Xubuntu, firefox, netbeans and MDB FREE 4.5.13 
### Resources (screenshots, code snippets etc.)
to solve the issue, in[ scss/core/_global.scss](https://github.com/mdbootstrap/bootstrap-material-design/blob/0c82be3f823d3263698d5313f469e44d5b8d0f0c/scss/core/_global.scss#L105) , it's possible to add the variable `$link-hover-color` under
```
a{
   a:hover{
      color: $link-hover-color 
   }
}
```

`$link-hover-color` will also need to be added to the default _variables.scss file.

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by Martussky** [comment]
Hi,
could you provide any details of your problem? Any code or demo or create a snippet showing the issue here: [https://mdbootstrap.com/snippets/](https://mdbootstrap.com/snippets/)?
Best,
Marta

**Comment by mattonit** [comment]
Closing due to no response
