### ISSUE TITLE
Website is DOWN AGAIN!

### ISSUE THREAD

**Issue by infatti** [mdbootstrap/bootstrap-material-design#204]
https://mdbootstrap.com/ documentation site is down again. It has been down for the last 2 weeks I have attempted to access the documentation! This seems very suspicious. We paid for the MDBootstrap Pro package and if you cannot keep basic documentation online we will consider you an untrustworthy resource. Any response to this?

**Comment by mattonit** [comment]
Please contact me at b.malanowski@mdbootstrap.com. In your e-mail, please provide us your e-mail address. It's possible that it's blocked by our firewall

**Comment by infatti** [comment]
I sent you an email from JMoore@kleinfelder.com. Did you receive it?

Jay

**Comment by mattonit** [comment]
Yes, I did. Can't wait to get a response from you!

**Comment by mattonit** [comment]
Closed due to no response
