### ISSUE TITLE
fadeIn animation bug

### ISSUE THREAD

**Issue by mcwnuq** [mdbootstrap/bootstrap-material-design#206]
### Expected behavior
fadeIn animation trigger on page load ( element is visible on screen )

### Actual behavior
animation trigger twice:
1. when page load
2. when start scrolling

### Your working environment and MDB version information
MDB version > 4.5.16
Chrome > Wersja 71.0.3578.98 (Oficjalna wersja) (64-bitowa)

### Resources (screenshots, code snippets etc.)
code >
https://gist.github.com/mcwnuq/cc4bc12f5831bf805a72595840e433e4
video >
https://www.youtube.com/watch?v=cmLMtZ5PKFs

**Comment by Martussky** [comment]
Hi, 
we created a task with this issue and we will fix that as soon as possible. Thank you for noticing this.
Best, Marta

**Comment by aditya1906** [comment]
According to your code you have used .wow class. That triggers the animation on scroll. Let me know if I'm mistaken.

**Comment by PiotrObrebski** [comment]
Did you try implementing it according to suggestions from the docs?
https://mdbootstrap.com/docs/jquery/css/animations/
add visibility: hidden; to the wow
"Thanks to that you avoid reloading the content after javascript load."
