### ISSUE TITLE
Git complaining about line endings in SVG files

### ISSUE THREAD

**Issue by jurgenhaas** [mdbootstrap/bootstrap-material-design#215]
The SVG files in the img/svg directory have CRLF line endings which git always replaces with LFs only. When using these files in your own project where you commit the assets as well, you always get complaints from git at the command line.

Is it possible to cleanup those files and deliver them with LFs only?

**Comment by mattonit** [comment]
I've added this issue to our TODO list so I hope we'll fix it soon. You can also fix it by yourself and make us a PR so I'll merge it

**Comment by jurgenhaas** [comment]
@mattonit I'm confused. I have created the PR already over a year ago, it got checked and everything. And just now, @gbujanski closes my PR without merging and at the same time, you're asking me I should create a PR. What's going on?
