### ISSUE TITLE
[4.7.3] "scss/core" directory is missing in the npm package

### ISSUE THREAD

**Issue by jfcherng** [mdbootstrap/bootstrap-material-design#217]
### Actual behavior
As the title. Thus we are not able to built from SCSS.
People have to manually copy them from github source codes.

### Your working environment and MDB version information
MDB free 4.7.3
Yarn 1.13.0

**Comment by mattonit** [comment]
It's a bug with NPM 6.8.0. [They promised](https://npm.community/t/npm-pack-leaving-out-files-6-8-0-only/5382/10) to fix it in the 6.9.0 release

**Comment by jfcherng** [comment]
@mattonit Got it. Thanks for this info.

**Comment by isabasan** [comment]
NPM 6.9 released...
