### ISSUE TITLE
Date Picker is not working.

### ISSUE THREAD

**Issue by salehST** [mdbootstrap/bootstrap-material-design#219]
### Expected behavior
Date Picker isn't working.
### Actual behavior
I am doing exactly shown on your site. But. it's showing up the calendar. also, the dropdown is not working.
### Your working environment and MDB version information
I am useing the lastet version of MDB 4.7.3
### Resources (screenshots, code snippets etc.)
this is the HTML code: http://prntscr.com/mpd0di
this is the js code. http://prntscr.com/mpd00t

**Comment by mattonit** [comment]
Date Picker is a premium component and won't work with MDB Free
