### ISSUE TITLE
Editing buttons of sortable table disappear

### ISSUE THREAD

**Issue by JeanPaulvB** [mdbootstrap/bootstrap-material-design#220]
The issue appears with the table editor, sortable rows example on the mdb documentation website:

[https://mdbootstrap.com/plugins/jquery/table-editor/#extended-rows](https://mdbootstrap.com/plugins/jquery/table-editor/#extended-rows)

### Expected behavior

Editing buttons for other rows should not disappear/ be disabled after editing a row

### Actual behavior

Editing buttons for other rows disappear/ are disabled after editing a row

### Your working environment and MDB version information

I'm using the mdb documentation website here , which runs MDB v4.7.3 [see source](https://mdbootstrap.com/wp-content/themes/mdbootstrap4/js/4.7.3/compiled.1.min.js?ver=4.7.3)

### Resources (screenshots, code snippets etc.)

The gif speaks for itself: 

# [gif screen capture of the issue](https://i.imgur.com/sBGZjt8.gif)

**Comment by pglejzer** [comment]
Thanks for your topic, its bug, we will fix that as soon as possible. Have a nice day.

**Comment by pglejzer** [comment]
I fixed this. If you want fix this at the moment you have to go to your mdb-editor js file and chagne function saveRowClickRemoveDiv for this --> 

>         saveRowClickRemoveDiv = function () {
> 
>           $(this).find('.div-to-remove').remove()
>         },

we will fix that globally in next release.

**Comment by JeanPaulvB** [comment]
That's what I call quick support. Awesome, thanks!
