### ISSUE TITLE
npm error EISGIT on npm install

### ISSUE THREAD

**Issue by aabuhijleh** [mdbootstrap/bootstrap-material-design#221]
I use this module in my project and up until very recently it was working fine. 

Now it causes this error on npm install in my project...

```sh
npm ERR! path /builds/aabuhijleh/electron_desktop/rb-services/node_modules/mdbootstrap
npm ERR! code EISGIT
npm ERR! git /builds/aabuhijleh/electron_desktop/rb-services/node_modules/mdbootstrap: Appears to be a git repo or submodule.
npm ERR! git     /builds/aabuhijleh/electron_desktop/rb-services/node_modules/mdbootstrap
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

the issue is solved by

```sh
rm -rf node_modules/mdbootstrap/.git/
```

the git repository should be removed from the package.

mdbootstrap v4.7.4
used in electron
OS: both Windows 7 and Ubuntu

**Comment by mattonit** [comment]
how can we recreate this issue?

**Comment by aabuhijleh** [comment]
For me, this is very simple to reproduce...

I created a clean empty project with ```npm init``` then 

```sh
npm i mdbootstrap@latest
```

then firing ```npm install``` produces that EISGIT error because the ```.git/``` folder in included in the package.

if you installed mdbootstrap@4.7.3 you won't get this error because the ```.git/``` folder is not included in that package

**Comment by mattonit** [comment]
It's an awful issue, but with the next update we'll fix it up

**Comment by isabasan** [comment]
its 4.7.6 now and issue is still open.
```
npm ERR! code EISGIT
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by aabuhijleh** [comment]
This seems to be resolved in @4.8.0.

**Comment by jackryu** [comment]
@aabuhijleh - Thanks for the solution...

**Comment by ramiasg** [comment]
+1

**Comment by deepankarsandy** [comment]
`npm install --save react-native-markdown-renderer
npm ERR! path /Users/user/Source/tikkl/app/node_modules/react-native-push-notification
npm ERR! code EISGIT
npm ERR! git /Users/user/Source/app/node_modules/react-native-push-notification: Appears to be a git repo or submodule.
npm ERR! git     /Users/sandy/Source/app/node_modules/react-native-push-notification
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-06-07T04_08_53_731Z-debug.log`

**Comment by RahulNainwal** [comment]
i am geting the same error @deepankarsandy

**Comment by deepankarsandy** [comment]
You need to `rm -rf` .git from that node modules directory, that solved my issue
