### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by hyandell** [mdbootstrap/bootstrap-material-design#222]
Could you confirm whether or not the version of MDB downloaded from https://www.npmjs.com/package/mdbootstrap is 100% under the MIT license, or does it contain commercial/proprietary licensed content?

From the download, it's not clear to me whether https://www.npmjs.com/package/mdbootstrap contains any part of the product referred to as "MDB PRO & Bundles & Templates & Plugins (jQuery, Angular, React, Vue versions)".

**Comment by marveluck** [comment]
Hi, this package is fully covered by MIT license, it's free and unrestricted for personal and commercial use. It doesn't contain any paid product.

**Comment by Maidah5** [comment]
ok sir thank you for informing me

**Comment by hyandell** [comment]
Thank you Mateusz :)
