### ISSUE TITLE
Chrome 73 mouseup timepicker popup disappears

### ISSUE THREAD

**Issue by warmwhisky** [mdbootstrap/bootstrap-material-design#225]
### Expected behavior
Time picker should stay open on click
### Actual behavior
Time picker disappears on mouseup. If the user right clicks the time picker stays open.
### Your working environment and MDB version information
Windows 7 and 10 Chrome 73
This is happening also on your website https://mdbootstrap.com/docs/jquery/forms/time-picker/

I have confirmed this behavior on 3 computers running Chrome 73. Also I have tried this on a PC running Chrome 72 and after updating to 73 the problem was apparent.

**Comment by pglejzer** [comment]
Hello. We already fix this on version 4.7.5. Check our docs now. Have a nice day.

**Comment by HomeSeer** [comment]
I am on mdbootstrap 4.8.4 and I am still seeing this issue. Where was this fixed? The problem is still on this page:

https://mdbootstrap.com/docs/jquery/forms/time-picker/
