### ISSUE TITLE
A link button in a table got color over written

### ISSUE THREAD

**Issue by jayskyworker** [mdbootstrap/bootstrap-material-design#227]
### Expected behavior
a Link button Inside a table should follow the text color of btn
```
<table class=table><tr><td>
 <a class="btn btn-primary " href="/">test</a>
</td></tr><table>
```

### Actual behavior
mdb.css:8405 table.table a overwrites the text color and make all text black

### Your working environment and MDB version information
4.7.5
### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by Martussky** [comment]
Hi,
we will fix that in the next release and we will inform about this in our changelog.
Best, Marta
