### ISSUE TITLE
表单验证我怎么知道验证通过了呀？

### ISSUE THREAD

**Issue by xiaoxiaoyuanwang** [mdbootstrap/bootstrap-material-design#228]
<template>
  <mdb-container class="mt-5">
    <form class="needs-validation" novalidate @submit="checkForm">
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="validationCustom01">First name</label>
          <input type="text" class="form-control is-valid" id="validationCustom01" placeholder="First name" value="Mark" required>
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <label for="validationCustom02">Last name</label>
          <input type="text" class="form-control is-valid" id="validationCustom02" placeholder="Last name" value="Otto" required>
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <label for="validationCustomUsername">Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroupPrepend">@</span>
            </div>
            <input type="text" class="form-control" id="validationCustomUsername" placeholder="Username" aria-describedby="inputGroupPrepend" required>
            <div class="invalid-feedback">
              Please choose a username.
            </div>
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-6 mb-3">
          <label for="validationCustom03">City</label>
          <input type="text" class="form-control  " id="validationCustom03" placeholder="City" required>
          <div class="invalid-feedback">
            Please provide a valid city.
          </div>
        </div>
        <div class="col-md-3 mb-3">
          <label for="validationCustom04">State</label>
          <input type="text" class="form-control  " id="validationCustom04" placeholder="State" required>
          <div class="invalid-feedback">
            Please provide a valid state.
          </div>
        </div>
        <div class="col-md-3 mb-3">
          <label for="validationCustom05">Zip</label>
          <input type="text" class="form-control  " id="validationCustom05" placeholder="Zip" required>
          <div class="invalid-feedback">
            Please provide a valid zip.
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="form-check pl-0">
          <input class="form-check-input  " type="checkbox" value="" id="invalidCheck" required>
          <label class="form-check-label" for="invalidCheck">
            Agree to terms and conditions
          </label>
          <div class="invalid-feedback">
            You must agree before submitting.
          </div>
        </div>
      </div>
      <mdb-btn type="submit">Submit form</mdb-btn>
    </form>
  </mdb-container>
</template>
<script>
  import { mdbContainer, mdbBtn } from "mdbvue";
  export default {
    name: "InputsPage",
    components: {
      mdbContainer,
      mdbBtn
    },
    methods: {
      checkForm(event) {
        event.preventDefault();
        event.target.classList.add('was-validated');
      }
    }
  }
</script>
![image](https://user-images.githubusercontent.com/22828691/54763294-b3313b00-4c30-11e9-803f-757586ec99af.png)

**Comment by mattonit** [comment]
Oh no! It looks like you've mistaken repositories. This repository is dedicated to MDB jQuery, but your issue is with MDB Vue which is a younger brother of MDB jQuery. In this case, I recommend you to ask your question on the right category on our [official forum](https://mdbootstrap.com/support/cat/vue/) or [open your issue here](https://github.com/mdbootstrap/vue-bootstrap-with-material-design)
