### ISSUE TITLE
Javascript dependencies

### ISSUE THREAD

**Issue by bugduino** [mdbootstrap/bootstrap-material-design#23]
This library provides a big file (more than 5000 lines) called `mdb.js` in the `js` folder of the repo which includes all the dependencies that you are using (e.g jquery-easing.js ,global.js, velocity.js, etc) and some initialization options. I would have expected to find a small js file and all dependecies listed in the `bower.json` or `package.json` so that they could be installed through `bower install` or `npm install`. Am I missing something?

**Comment by mattonit** [comment]
Thanks for the tip! We'll take a look at this

**Comment by bugduino** [comment]
In the Pro version I see that js modules are present, I would advertise that :)
