### ISSUE TITLE
Error establishing a database connection on website

### ISSUE THREAD

**Issue by Deepakchawla** [mdbootstrap/bootstrap-material-design#232]
### Expected behavior
working website 
### Actual behavior
Error establishing a database connection error
### Your working environment and MDB version information
it is website information
### Resources (screenshots, code snippets etc.)
![Screenshot from 2019-04-21 11-24-34](https://user-images.githubusercontent.com/10181936/56466083-483e7400-6429-11e9-843a-aece77b21816.png)
![Screenshot from 2019-04-21 11-24-29](https://user-images.githubusercontent.com/10181936/56466085-48d70a80-6429-11e9-9721-a7852b47c1f8.png)

**Comment by mattonit** [comment]
As I can see, everything is working. I can't see downtime on our monitors. Is the problem still occur?

**Comment by Deepakchawla** [comment]
Yeah it is still at my system and this is latest screen shot
![Screenshot from 2019-04-21 15-00-12](https://user-images.githubusercontent.com/10181936/56468193-2d2e2d00-6446-11e9-9164-0c78e05a372d.png)

**Comment by mdbootstrap** [comment]
@Deepakchawla  - apparently one out of 3 our servers had networking issue while connecting with database server. The issue has been solved now. My apologies for your inconvenience.

**Comment by Deepakchawla** [comment]
yeah, now it's working fine. thanks to fixing it
