### ISSUE TITLE
File Input Forms Broken

### ISSUE THREAD

**Issue by spencerthayer** [mdbootstrap/bootstrap-material-design#233]
### Expected behavior

For file input forms to look [like they do in the documentation](https://mdbootstrap.com/docs/jquery/forms/file-input).

### Actual behavior

The file input forms [look broken](https://codepen.io/spencerthayer/pen/BEgLzq).

### Your working environment and MDB version information

*   [CodePen](https://codepen.io/spencerthayer/pen/BEgLzq)
*   [twitter bootstrap css 4.3.1](https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css)
*   [mdbootstrap css 4.7.7](https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.7/css/mdb.min.css)
*   [fontawesome css 5.8.1](https://use.fontawesome.com/releases/v5.8.1/css/all.css)
*   [jquery js 3.3.1](https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js)
*   [popper js 1.14.4](https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js)
*   [twitter bootstrap js 4.3.1](https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js)
*   [mdbootstrap js 4.7.7](https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.7/js/mdb.min.js)

### Resources (screenshots, code snippets etc.)

Everything is at [CodePen](https://codepen.io/spencerthayer/pen/BEgLzq).

### Crossposted
- [GitHub](https://github.com/mdbootstrap/bootstrap-material-design/issues/233)
- [MD Bootstrap Support](https://mdbootstrap.com/support-ask-question/?id=97441)

**Comment by pglejzer** [comment]
It's not broken. You are using a free version in codepen so this is a reason why this is broken for you. If you will use our PRO version this will be work normally. I close this issue.
