### ISSUE TITLE
I DONT KNOW WHY THE RELEASES IS ALWAYS BROKEN

### ISSUE THREAD

**Issue by mannok** [mdbootstrap/bootstrap-material-design#234]
I DONT KNOW WHY THE RELEASES IS ALWAYS BROKEN

**Comment by Martussky** [comment]
Hi,
would you describe the problem you have with our package?
Best, Marta

**Comment by mattonit** [comment]
Closed due to no response

**Comment by mannok** [comment]
npm i mdbootstrap will get a broken module.   Wrong main file in package.json
