### ISSUE TITLE
md-form ... input type "week" and "month"

### ISSUE THREAD

**Issue by ThierryNapspirit** [mdbootstrap/bootstrap-material-design#235]
Why don't you add support to input "week" and "month" using "md-form".

**File**: "scss/free/_forms.scss".

At the beginning, after `input[type=datetime-local]` insert  ` input[type=week], input[type=month],`.

Then insert on line 112:

```
    >input[type=week]:not(.browser-default)+label {
        transform: translateY(-27px) scale(0.8);
        transform-origin: 0 0;
    }
    >input[type=month]:not(.browser-default)+label {
        transform: translateY(-27px) scale(0.8);
        transform-origin: 0 0;
    }

```

Thanks.

Best regards.
Thierry

**Comment by pglejzer** [comment]
Hi. I added your solution to our list to do. We are gonna think about it and we will test it and if everything will good, we gonna add to our packages. Have a nice day.
