### ISSUE TITLE
Use MDB Bootstrap For One Part Only

### ISSUE THREAD

**Issue by fakhamatia** [mdbootstrap/bootstrap-material-design#237]
How i can use MDB for only one tag ? For example i want only use MDB Table but other things in page use normal Bootstrap not MDB.

**Comment by Martussky** [comment]
Hi,
which version of MDB do you use? Standard or Gulp one?
Best, Marta

**Comment by fakhamatia** [comment]
MDB 4.7.5 , Standard 

> Hi,
> which version of MDB do you use? Standard or Gulp one?
> Best, Marta

MDB 4.7.5 , Standard

**Comment by Martussky** [comment]
Hi,
if you use MDB Gulp version, you will comment or delete in `mdb.scss` file all unnecessary imported files and then recompile `mdb.css` file and you will have your own mdb.css file with only needed styles. So, if you want to use only part of MDB styles, please download and use **MDB Gulp Free package**.
Best, Marta

**Comment by PiotrObrebski** [comment]
You can do the same thing with our js using gulp package. In modules.js remove all elements you don't want to use and compile our package using gulp. You can find all needed information about customization of our package in this tutorial: https://mdbootstrap.com/education/bootstrap/gulp-installation/
