### ISSUE TITLE
This dependency was not found: mdbootstrap

### ISSUE THREAD

**Issue by mannok** [mdbootstrap/bootstrap-material-design#242]
### Expected behavior
Project loads successfully
### Actual behavior
index.js could not be found
### Your working environment and MDB version information
v4.8.1
### Resources (screenshots, code snippets etc.)
Refer to package.json, the main file is pointed to index.js while which is not exist in the module root.

**Comment by donaldinou** [comment]
Should be fast to fix. ;)
