### ISSUE TITLE
Chrome security error

### ISSUE THREAD

**Issue by zacny** [mdbootstrap/bootstrap-material-design#247]
### Expected behavior
The page is loading without security errors.
### Actual behavior
When loading the page, chrome browser is notifing on security problems.
### Your working environment and MDB version information
4.8.2
### Resources (screenshots, code snippets etc.)
In file mdb.min.css I found unsecure links like:
.navbar-toggler-icon{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns=**'http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.9)**' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");cursor:pointer}
If I changed http to https everythings is allright.

**Comment by zacny** [comment]
This doesn't solve my problem.

**Comment by mattonit** [comment]
@zacny why did you close this issue?
