### ISSUE TITLE
0.6rem is too small for the .btn-sm

### ISSUE THREAD

**Issue by eric6356** [mdbootstrap/bootstrap-material-design#25]
Hi, I'm updating MDB to 4.2 and I find the new font-size for .btn-sm is too small.

.btn-sm is 0.875rem in bootstrap
MDB 4.2 override it to 0.6rem

I think it is OK only for uppercase English letters.
When it comes to Chinese characters, I can hardly see 0.6rem characters clearly even in my Retina display monitor. It must be worse in a normal 1x monitor.
MDB 4.1.1 ↓
<img width="108" alt="screen shot 2016-11-10 at 20 43 44" src="https://cloud.githubusercontent.com/assets/6096443/20177208/8e32ceb4-a786-11e6-85e1-9ce5ff0dfd4f.png">

MDB 4.2↓
<img width="115" alt="screen shot 2016-11-10 at 20 43 57" src="https://cloud.githubusercontent.com/assets/6096443/20177222/9cf8e186-a786-11e6-8579-bd1863babb0e.png">

Will you consider change it back in future versions?

**Comment by eric6356** [comment]
Another example, Traditional Chinese characters.
MDB 4.1.1↓
![screen shot 2016-11-10 at 21 15 40](https://cloud.githubusercontent.com/assets/6096443/20178180/0ecc49a2-a78b-11e6-91bf-fac20936e1c5.png)

MDB 4.2↓
![screen shot 2016-11-10 at 21 15 48](https://cloud.githubusercontent.com/assets/6096443/20178202/1a332b3a-a78b-11e6-8214-95e926b5ebbf.png)

These screen shots are made on my DELL U2415 monitor, 1920*1080, 24", quite normal one.
I think 0.6rem is definitely too small.

**Comment by mattonit** [comment]
What size would be perfect for you?

**Comment by eric6356** [comment]
Thanks for you attention.
Personally, I think bootstrap's original 0.875rem is fine.
I don't have any trouble in customizing font size for myself, just think 0.6rem might be an issue and want to point it out.
:)

**Comment by mattonit** [comment]
We'll take a look at this. Thanks for suggestion ;)
