### ISSUE TITLE
TypeError: e is null

### ISSUE THREAD

**Issue by reckerswartz** [mdbootstrap/bootstrap-material-design#250]
console showing error on this line don't know why 

![Screenshot from 2019-06-27 04-48-21](https://user-images.githubusercontent.com/16918568/60221329-e110c600-9896-11e9-923e-622d252134cd.png)

https://github.com/mdbootstrap/bootstrap-material-design/blob/61af89d242e36dea4f530dc0019230b60a58b5d1/js/mdb.js#L15413

Edit: found the issue I am using rails and initializing MDB in the head tag.
so The body hasn't been defined at this point yet.
You want to wrap this code in a window.onload handler

**Comment by PiotrObrebski** [comment]
Problem with initializing mdb in header will be fixed in next the release. https://github.com/mdbootstrap/bootstrap-material-design/issues/49
