### ISSUE TITLE
Fixed buttons - animation

### ISSUE THREAD

**Issue by locddspkt** [mdbootstrap/bootstrap-material-design#251]
### Expected behavior
Stop the animation when move out the button
### Actual behavior
When move out the button, the sub buttons is scrolled up and down infinitively 
### Your working environment and MDB version information
On the demo page jquery md bootstrap
### Resources (screenshots, code snippets etc.)
Screenshot: https://www.dropbox.com/s/klp3b7que76n4dx/Screen%20Recording%202019-06-27%20at%2015.47.59.mov?dl=0

**Comment by mateuszlubianka1993** [comment]
Hi,
We fixed this issue in the last mdb version.
