### ISSUE TITLE
carousel code is fading and not sliding between pictures

### ISSUE THREAD

**Issue by maximegheraille** [mdbootstrap/bootstrap-material-design#252]
### Expected behavior
carousel slideshow (reactjs)
### Actual behavior
it is fading and not sliding while having the same code
### Your working environment and MDB version information
reacts version 4.17
Mac OS Mac OS 10.15 Beta 3 with chrome/safari
### Resources (screenshots, code snippets etc.)
added MDBootstrap via $ npm install --save mdbreact
added the 3 imports in my index.
and copy pasted the carousel example from the site 

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by maximegheraille** [comment]
I just saw the code was updated and they added a slide parameter in de MDBCarousel.
It does changes the effect from fading to know just switching between pictures but it still does not slide between the pictures

**Comment by mateuszlubianka1993** [comment]
Hi,
There are react issues: https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/issues
