### ISSUE TITLE
Modal form examples have form fields but there is no form element in the HTML

### ISSUE THREAD

**Issue by ppazos** [mdbootstrap/bootstrap-material-design#254]
Ref https://mdbootstrap.com/docs/jquery/modals/forms/

Expected: there should be some form elements in order to submit data.

**Comment by mattonit** [comment]
Thank you for sharing your idea. I've added this to our customers' wish list. However, please take a look at the "Edit these docs" button attached to our docs pages. It's a way to help us to change our documentation
