### ISSUE TITLE
MDB3 documentation not working

### ISSUE THREAD

**Issue by halfer** [mdbootstrap/bootstrap-material-design#255]
I have been trying to access the MDB 3 docs for the last week, to no avail. For example:

https://mdbootstrap.com/mdb3/css/colors/

I have tried a variety of browsers but they all do not work. The white content area appears to be ~80 pixels tall for every MDB 3 page, and no context is visible. I have tried several browsers, on Linux and on Windows 10. I have tried several pages in the MDB 3 docs.

**Comment by halfer** [comment]
Are these documents available elsewhere, such as in a GitHub repo?

**Comment by halfer** [comment]
Hi @Martussky - the commit log suggests you are the release manager for MDB. May I trouble you for an answer to the above? That version 3 docs are on the main site suggest that it is still officially supported.

**Comment by mattonit** [comment]
@halfer, a long time ago we've moved the docs for MDB 3 [here](https://mdbootstrap.com/legacy/jquery/3.4.1/)

**Comment by halfer** [comment]
Ah, marvellous - thank you @mattonit. I don't recall how I came by the link I have cited, but could you get that whole `/mdb3/` subfolder to redirect to the new location? Or just a link in the content space.
