### ISSUE TITLE
Dropdown menu not beavhing correctly. 

### ISSUE THREAD

**Issue by shawnstom** [mdbootstrap/bootstrap-material-design#259]
### Expected behavior
For the dropdown menu to nicely fade in like this example in this snippet.
https://mdbootstrap.com/snippets/jquery/temp/1329273?action=prism_export

### Actual behavior
Its just popping on and popping off and kinda of delayed and as instant as the example.
It appears the animated class and fadein and fadeout classes are not being applied. I made sure to apply the js files in the order given on the getting started page on MDB.

http://parksidepediatrics.wpserver.cloud/

### Your working environment and MDB version information
I grabbed the lastest version 4.8.10 to make sure I had the latest files. I am using scss and gulp for my styles. 

for JS i am using the mdb.min.js which is enqueued in my functions.php

**Comment by mateuszlubianka1993** [comment]
Hi,
Our team will check this soon. Thank you very mutch for this post.

**Comment by gbujanski** [comment]
Dropdown animations are only available in the MDB Pro.
