### ISSUE TITLE
responsive heading styles missing in version 4.8.11

### ISSUE THREAD

**Issue by leightonsmith** [mdbootstrap/bootstrap-material-design#260]
### Expected behavior
responsive styles for headings (e.g. h3-responsive) are available

### Actual behavior
they're missing

### Your working environment and MDB version information
using npm package version 4.8.11

### Resources (screenshots, code snippets etc.)
I'm not too familiar with sass, but it looks like the problem is the `!default` added to the end of this line https://github.com/mdbootstrap/bootstrap-material-design/blob/master/scss/core/_variables.scss#L99 in https://github.com/mdbootstrap/bootstrap-material-design/commit/82a34372320d9667f4d1f5a751bc3eda74d4e5f3#diff-252b35fc7cc2964fadc678c056766291

My understanding is that, as `$responsive-headings` is already defined before this statement (line 59), the `!default` will mean that `map-merge` function call will be ignored, and hence the value of $responsive-headings` will remain `()`, and so the classes for the responsive headings will not get initialised.

**Comment by mateuszlubianka1993** [comment]
Hi,
We will check this soon. Thank you ver much for this post.
Best,

**Comment by mateuszlubianka1993** [comment]
If you visit: https://mdbootstrap.com/docs/jquery/content/typography/#responsive-headings and open example in our mdb editor, you can see that responsive headings work well.
