### ISSUE TITLE
Update input text-fields according to latest Material Design guidelines

### ISSUE THREAD

**Issue by tholu** [mdbootstrap/bootstrap-material-design#261]
### Expected behavior

The input text-fields should use the latest Material Design guidelines.

### Actual behavior

The input text-fields use an older version of Material Design guidelines.

### Your working environment and MDB version information

I checked the latest MDB version on https://mdbootstrap.com/docs/jquery/forms/inputs/#input-fields (4.8.11).

### Resources (screenshots, code snippets etc.)

The current Material Design Guidelines for Text Fields can be found here:
https://material.io/components/text-fields/

<img width="820" alt="Screenshot 2019-11-06 13 26 29" src="https://user-images.githubusercontent.com/316763/68298195-0dd0b780-0099-11ea-9b1d-d1333d094e02.png">

The reasoning behind changing text fields in Material Design is explained here: https://medium.com/google-design/the-evolution-of-material-designs-text-fields-603688b3fe03

**Comment by Martussky** [comment]
Hi,

we add this type of input in the future. Thank you for remind.

Best, Marta

**Comment by tholu** [comment]
Thanks for the quick response. Is there an ETA for this?

**Comment by Martussky** [comment]
Hi,

No, we don't have ETA for this.

Best, Marta

**Comment by tholu** [comment]
@mateuszlubianka1993 Was this already implemented?
