### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by phillipjacobs** [mdbootstrap/bootstrap-material-design#265]

**Comment by mattonit** [comment]
As I can see, everything is working fine. If you’re having issues with accessing our website, please try to clear your DNS cache. If this doesn’t help, please contact our support team at support@mdbootstrap.com

**Comment by phillipjacobs** [comment]
on ping to mdbootstrap.com, i'm getting significant packet loss.

**Comment by phillipjacobs** [comment]
Thanks @mattonit , Should have tried that before logging an issue.

Thanks again...

**Comment by phillipjacobs** [comment]
Thanks @mattonit , Should have tried that before logging an issue.

Thanks again...

**Comment by phillipjacobs** [comment]
Thanks @mattonit , Should have tried that before logging an issue.

Thanks again...
