### ISSUE TITLE
Please contact me at b.malanowski@mdbootstrap.com. In your e-mail, please provide us your e-mail address. It's possible that it's blocked by our firewall

### ISSUE THREAD

**Issue by FansaIT** [mdbootstrap/bootstrap-material-design#267]
Please contact me at b.malanowski@mdbootstrap.com. In your e-mail, please provide us your e-mail address. It's possible that it's blocked by our firewall

_Originally posted by @mattonit in https://github.com/mdbootstrap/bootstrap-material-design/issues/204#issuecomment-443991426_

**Comment by FansaIT** [comment]
I believe I was blocked by your firewall, I emailed b.malanowski@mdbootstrap.com
I just purchased MDB Pro, and for some reason, I can not view the site from any computer in my network? The site is up, but not from my side, any possibility I have been blocked?

**Comment by mattonit** [comment]
@FansaIT I didn't receive any e-mail from you. Please try to contact me again or send an e-mail at support@mdbootstrap.com with your IP address so I could check that

**Comment by FansaIT** [comment]
Thank you, I resolved the issue
