### ISSUE TITLE
Accordion does not work as expected

### ISSUE THREAD

**Issue by bugduino** [mdbootstrap/bootstrap-material-design#27]
In the MDB-Pro 4.2.0 , I have included all scss file and all js modules in my app (specifically also the `collapsible.js` module) and copied your example template for accordion
`

<div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">

    
    <div class="panel panel-default">

        
        <div class="panel-heading" role="tab" id="headingOne">
            <h5 class="panel-title">
                <a class="arrow-r" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-   expanded="true" aria-controls="collapseOne"> Collapsible Group Item #1<i class="fa fa-angle-down rotate-icon"></i>
                </a>
            </h5>
        </div>

        
        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
            on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table,
            raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </div>
    </div>
    

    
    <div class="panel panel-default">

        
        <div class="panel-heading" role="tab" id="headingTwo">
            <h5 class="panel-title">
                <a class="arrow-r" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseOne">
                   Collapsible Group Item #2<i class="fa fa-angle-down rotate-icon"></i>
                </a>
           </h5>
        </div>

        
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
            on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table,
            raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </div>
    </div>
    

    
    <div class="panel panel-default">

        
        <div class="panel-heading" role="tab" id="headingThree">
            <h5 class="panel-title">
                <a class="arrow-r" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="true" aria-controls="collapseOne">
                    Collapsible Group Item #3<i class="fa fa-angle-down rotate-icon"></i>
                </a>
            </h5>
        </div>

        
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
            on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table,
            raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </div>
    </div>
    

</div>

`

but it does not work as expected: when clicking on an element the arrow icon is not rotated and clicking on a panel does not collapse other panels already open in the same accordion, why?

**Comment by mattonit** [comment]
[Here](http://mdbootstrap.com/javascript/collapse/#accordion) you can find working example of accordion

**Comment by bugduino** [comment]
The problem is that the example given (and copied above) from mdb site seems to not work properly
