### ISSUE TITLE
unable to visit mdbootstrap official website in china now, due to the unavailability of the cdn - z9t4u9f6.stackpathcdn.com

### ISSUE THREAD

**Issue by xinheblue** [mdbootstrap/bootstrap-material-design#270]
Hi,

The MDBoostrap is awesome,  and I have bought the Pro Version, and these days, I found that I could n't visit the offical website,  and couldn't read the document, and are not convenient.

The reason is that your cdn server cann't be reached in China, z9t4u9f6.stackpathcdn.com, previously it's not a problem.

Would you please solve this problem?

**Comment by filipkappa** [comment]
Hello,

I'm Filip from MDB. Thank you for reaching out.

Can you share some more details that would help us a lot.

What city, State and ISP do you use?

And are they able to provide some MTR and TCP traceroute tests from your
side towards our page?

If you need anything else please let me know.

Best regards,
Filip from MDB

niedz., 12 sty 2020 o 13:05 xinheblue <notifications@github.com> napisał(a):
