### ISSUE TITLE
Select not applyin selected on selection

### ISSUE THREAD

**Issue by vosco88** [mdbootstrap/bootstrap-material-design#271]
### Expected behavior
Select should mark selected option

### Actual behavior
Selected option stays the same

### Your working environment and MDB version information
MDB Pro 4.12

### Resources (screenshots, code snippets etc.)
![image](https://user-images.githubusercontent.com/14372933/73616907-53117080-4619-11ea-8d1e-d88a97b761b7.png)

When I select another item from the dropdown the selected mark stays on the one it is on.

**Comment by mateuszlubianka1993** [comment]
Hi,
As you can see on MDB docs, the frirst `<option></option>` should be selected. Like here:
`<option selected>Open this select menu</option>`.
If you copy the code from our docs, it should works well

Best,

**Comment by vosco88** [comment]
My selected option is coming from the database so that is why I do not have the first option selected. 
However even if I go here https://mdbootstrap.com/docs/jquery/forms/select/ and try the first form it does not work. 
This is the state when there is 'Open this select menu' in the select form
![image](https://user-images.githubusercontent.com/14372933/73935806-b2a1a180-48e1-11ea-9102-0600e8ea6afa.png)
And this is the state when I select one of the other options 
![image](https://user-images.githubusercontent.com/14372933/73935889-e11f7c80-48e1-11ea-8b4e-279d1cd3daa5.png)
So the selected tag does not move around which I think is telling the form that always the same item is selected.

**Comment by mateuszlubianka1993** [comment]
When selected attribute present, it specifies that an option should be pre-selected when the page loads.
If you choose one of the options and consol value, you will see value from option that you selected.
