### ISSUE TITLE
Web site mdbootstrap.com is not working

### ISSUE THREAD

**Issue by mkaliberda** [mdbootstrap/bootstrap-material-design#273]
![image](https://user-images.githubusercontent.com/19783885/75058542-dec54100-54e3-11ea-814f-dc6e72acf302.png)

**Comment by vabarboza** [comment]
Here I have this same problem.

**Comment by mateuszlubianka1993** [comment]
Hi,
We had a problem with the site last Friday but everything works well now.

**Comment by noticeeverything** [comment]
I still cannot access your site. ERR_CONNECTION_TIMED_OUT
