### ISSUE TITLE
Site mdbootstrap.com is hacked

### ISSUE THREAD

**Issue by andrey-vk** [mdbootstrap/bootstrap-material-design#284]
Site mdbootstrap.com is hacked. It serves js.Redirector.net trojan

**Comment by DerKamii** [comment]
I am surprised no one else noticed... Just wanted to get an hour of reading and now this. dang.

**Comment by cvbenur** [comment]
It's still going on, and no communication whatsoever... Fom what I've gathered the hack implanted malicious code into the pages, which appears to be a Trojan. Sources :
https://sitecheck.sucuri.net/results/www.mdbootstrap.com

**Comment by DerKamii** [comment]
Yes it is. You gotta be careful if you're using wordpress...

**Comment by cvbenur** [comment]
Thanks for the heads up. I should be good, I'm only using mdb for static pages on a school project since my group mates are not that good behind a computer...

**Comment by gbujanski** [comment]
We had a problem with "uninvited guests" but the situation is under control and everything was back to normal. We apologize for the inconvenience.

**Comment by noticeeverything** [comment]
I still cannot access your site. `ERR_CONNECTION_TIMED_OUT`

**Comment by gbujanski** [comment]
noticeeverything send to me your public IP adress to: g.bujanski@mdbootstrap.com. We will check this.
