### ISSUE TITLE
No Tags for this Project Breaks NPM and Bower builds

### ISSUE THREAD

**Issue by gscott-myorderwrite** [mdbootstrap/bootstrap-material-design#3]
Whatever was done 4 days ago deleted the tags that was being used by NPM and bower projects. Our project was dependent on version 0.5.10 and now we get the following error

[INFO] bower bootstrap-material-design#^0.5.10           cached https://github.com/mdbootstrap/bootstrap-material-design.git#0.5.10
[INFO] bower bootstrap-material-design#^0.5.10         validate 0.5.10 against https://github.com/mdbootstrap/bootstrap-material-design.git#^0.5.10
[INFO] bower bootstrap-material-design#^0.5.10     ENORESTARGET No tag found that was able to satisfy ^0.5.10
[INFO]
[INFO] Additional error details:
[INFO] No versions found in https://github.com/mdbootstrap/bootstrap-material-design.git

**Comment by jfretin** [comment]
Hello! Same here. My project broke when trying to deploy a new version, as it didn't find any tag for this lib.

**Comment by filipkappa** [comment]
@jfretin please check the repo now - the tags & npm install via tags should work properly

**Comment by jfretin** [comment]
@filipkappa Yes it works correctly (I'm still using bower for my project). Thanks a lot!

**Comment by Domynos** [comment]
Hello, this issue has come back today on bower.
Thanks in advance.

**Comment by gtzefrain** [comment]
I have the same issue.
Thanks for any help

**Comment by huergoG** [comment]
I am experiencing the same issue. Should this issue be reopened?
Thanks in advance.
