### ISSUE TITLE
Tabs not looks like Material Design

### ISSUE THREAD

**Issue by rafalradomski** [mdbootstrap/bootstrap-material-design#3]
[Material Design](https://material.google.com/components/tabs.html#tabs-usage)

![https://s3.postimg.io/8g10n2tcj/tab2.png](https://s3.postimg.io/8g10n2tcj/tab2.png)

[Angular Material](https://material.angularjs.org/latest/demo/tabs)

![https://s3.postimg.io/rz5lwfs43/tab3.png](https://s3.postimg.io/rz5lwfs43/tab3.png)

[MDB](http://mdbootstrap.com/components/tabs/#basic-example)

![https://s3.postimg.io/x80mubaj7/tab1.png](https://s3.postimg.io/x80mubaj7/tab1.png)

There is chance that you will add extra styling that be more similar to original tabs in Material Design?

**Comment by mdbootstrap** [comment]
They had this look before MDB 4.1 (so 2 weeks ago) but we decided (based on users feedback) it's one of the ugliest component in Material Design, so we changed it.

But yes, in the next update of MDB we will provide 2 versions of tabs - classic and ours.

**Comment by rafalradomski** [comment]
it fixed?

**Comment by mdbootstrap** [comment]
This week (or the beginning of the next one) we'll release new version of MDB with new Tabs.

**Comment by emman-ok** [comment]
The class material tab looks good on mobile but not on the web

**Comment by mattonit** [comment]
@emman-ok, could you please provide more details?
