### ISSUE TITLE
TypeError: body is null

### ISSUE THREAD

**Issue by ipepe** [mdbootstrap/bootstrap-material-design#31]
I included mdb.js in head and Im getting
```
TypeError: body is null
```
Code:
```javascript
   Waves.init = function (options) {
        var body = document.body;

        options = options || {};

        if ('duration' in options) {
            Effect.duration = options.duration;
        }

        if ('delay' in options) {
            Effect.delay = options.delay;
        }

        if (isTouchAvailable) {
            body.addEventListener('touchstart', showEffect, false);
            body.addEventListener('touchcancel', TouchHandler.registerEvent, false);
            body.addEventListener('touchend', TouchHandler.registerEvent, false);
        }

        body.addEventListener('mousedown', showEffect, false); //TypeError: body is null
    };
```
Error is marked on last line

**Comment by marktopper** [comment]
I think it should be added to the end of the body tag.

**Comment by mdbootstrap** [comment]
Dear ipepe, you are including js in head, due to that when website JS and try to assign body to the variable it cannot do this because this elements wasn't crated yeat (body tag is below head). You have to place your script below body.

**Comment by ipepe** [comment]
Lol, I know what happend. I just assumed that placing script src tags in head is something normal in modern WebDevelopment. I guess I will have to patch it myself.
