### ISSUE TITLE
Webpack support?

### ISSUE THREAD

**Issue by sebastianmacias** [mdbootstrap/bootstrap-material-design#32]
I haven't been able to build and include mdbootstrap with webpack. Does it support building with webpack?

**Comment by mattonit** [comment]
Please contact me at b.malanowski@mdbootstrap.com

**Comment by geomC** [comment]
I would also like to require mdbootstrap with webpack. What is the solution here?

**Comment by mattonit** [comment]
Hey guys,

I'm not sure if you remember this thread yet, but we've just published a tutorial that will help you to integrate MDB with Webpack: https://mdbootstrap.com/mdbootstrap-webpack-tutorial/
