### ISSUE TITLE
DXImageTransform.Microsoft.gradient

### ISSUE THREAD

**Issue by git-no** [mdbootstrap/bootstrap-material-design#34]
DXImageTransform.Microsoft.gradient gives a lot of CSS error in the browser console: "Unexpected CSS token".

DXImageTransform.Microsoft.gradient is [deprecated](https://msdn.microsoft.com/de-de/library/ms532997(v=vs.85).aspx) as with IE9.

So for Bootstrap 4 there is no need to have this CSS anymore. For cleaner, valid and better code I suggest to remove the DXImageTransform.Microsoft from MDBootstrap.

**Comment by mattonit** [comment]
DXImageTransform.Microsoft.gradient will be removed in the new version of MDB
