### ISSUE TITLE
v3.4.0 mdbootstrap and ui-router. waves-effect not working

### ISSUE THREAD

**Issue by coreystinson2** [mdbootstrap/bootstrap-material-design#4]
### Please note this is for version 3.4.0.

Hi,
I would like to share a problem and solution I came across this morning whilst integrating mdbootstrap with my application. My stack is routed with the angular ui-router component and I was noticing that none of my buttons were getting the waves-effect ripple animation.

After some debugging I found this to be due to when the Waves are initialized with the `displayEffect()` function.
```javascript
document.addEventListener('DOMContentLoaded', function () {
  Waves.displayEffect();
}, false);
```

With the angular ui-router component, the `DOMContentLoaded` method is fired prematurely to an application being fully loaded and instead I found hooking into the ui-router API event `$viewContentLoaded` to manually call the event, initialized the ripples properly.
```javascript
$rootScope.$on('$viewContentLoaded', function() {
  Waves.displayEffect();
});
```

My next foreseeable problem will be with modals when they are initialized, or any other DOM manipulation that doesn't come from the ui-router skipping the $viewContentLoaded event.
Will keep post updated.

**Comment by mdbootstrap** [comment]
Hi,

thank you for information. We'll keep in mind this issue.

Best Regards,
