### ISSUE TITLE
how to load mdbootstrap in an angular2 app using webpack?

### ISSUE THREAD

**Issue by AyzPat** [mdbootstrap/bootstrap-material-design#42]
want to include mdbootstrap in my angular2 app using webpack, not getting how to include it..

**Comment by AdrianSaw** [comment]
Hello AyzPat, 

We don't support angular yet.  However, many of out clients are using it with MDB, but it may take some developer skills to find all the needed solutions on your own.

Adrian

**Comment by mattonit** [comment]
@AyzPat recently, we have released MDB for Angular 2. Try this: https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design
