### ISSUE TITLE
Documentation :: undefined class :: .bd-highlight

### ISSUE THREAD

**Issue by NeonDevil** [mdbootstrap/bootstrap-material-design#43]
Bootstrap v4 uses `.bd-highlight` to show background-color and borders:
http://v4-alpha.getbootstrap.com/utilities/flexbox/

This class is undefined in the mdbootstrap docs and makes the examples hard to interpret:
https://mdbootstrap.com/css/flexbox/

**Comment by mattonit** [comment]
Thanks for noticing. I added this to our TODO list

**Comment by geoffreylzf** [comment]
is this TODO already do? I also confuse when seeing bd-sidebar and other.

**Comment by mattonit** [comment]
@geoffreylzf yes, this was resolved a long time ago
