### ISSUE TITLE
colors.scss ignores custom color setting

### ISSUE THREAD

**Issue by git-no** [mdbootstrap/bootstrap-material-design#45]
This is an issue already reported at Nov,16th, 2016 but is still not fixed even reported by user mattonit as will be fixed and issue https://github.com/mdbootstrap/bootstrap-material-design/issues/29 is closed.

Colors setting are broken after update to latest MDB release.
Scenario: I have a separate custom.scss with variable declarartions, loaded before mdb.scss.
Pre set color variable are ignored and oversteered by MDB.

## !default missing
This is how it is (from one item example from _colors.scss):
```scss
...
$secondary-color: #aa66cc;
...
```

This is it how it **shoud be**:
```scss
...
$secondary-color: #aa66cc !default;
...
```

This issue makes it impossible to oversteer color settings with an scss prior setting and makes a well scss structure impossible.

**Comment by mattonit** [comment]
fixed in MDB 4.4.1
