### ISSUE TITLE
Make border-radius a variable instead of hard coded

### ISSUE THREAD

**Issue by mikehutter** [mdbootstrap/bootstrap-material-design#5]
In your latest release, you opted for a 2px border radius with no way to easily override that setting.  I propose you add a variable to allow for a custom value in the _variables.scss file.

In my case, we prefer the square corners of most elements.

Thanks,

Mike

**Comment by mdbootstrap** [comment]
We use mixin to add a border-radius. It's very easy to change.

Go to sass/mdb/free/_global.scss and change "@include border-radius(2px);" to "@include border-radius(0px);

**Comment by mikehutter** [comment]
I already did find/do this, however that is one more place that I need to remember/find to modify when we get a new version from you.  If you are striving to make it as painless as possible for people to use and customize, keeping a setting like this in the _variables.scss file would make sense just like bootstrap does inside _variables-bs4.scss for its border radius.  That way when I want to update all I need to do is include my _variables.scss file before yours and I'm good.

**Comment by mdbootstrap** [comment]
I understand your point. However border-radius 2px is one of the core feature of Material Design and we didn't expect anyone would like to modify it. That's why it's not included in the file with variables. However we'll think about it.

**Comment by mdbootstrap** [comment]
➤ Michał Szymański commented:
To jest sassowy mixin, czyli coś w rodzaju zmiennej ktora akceptuje kilka css'owych deklaracji. 

@include border-radius(2px);

Koles moze to bardzo latwo zmienic po prostu zmieniajac 2px na 0 i kompilujac nowy plik
