### ISSUE TITLE
Update "main" field in package.json to follow npm spec

### ISSUE THREAD

**Issue by Apeopex** [mdbootstrap/bootstrap-material-design#52]
The "main" field should point to the javascript file so that `require()` calls can correctly look up the correct javascript file to import.

Spec Reference: [https://docs.npmjs.com/files/package.json#main](https://docs.npmjs.com/files/package.json#main)
Example from BS4: [https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L41](https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L41)

New "main" field in package.json should be `"main": "js/mdb"`

**Comment by mattonit** [comment]
I like that idea! This will be implemented in MDB 4.4.0

**Comment by maiorano84** [comment]
Seconding this.

**Comment by Apeopex** [comment]
For those using webpack, you can work around this for now by using the [resolve.alias](https://webpack.js.org/configuration/resolve/) option.

**Comment by mattonit** [comment]
Fixed with 8b5e346
