### ISSUE TITLE
SASS Setup Example Request

### ISSUE THREAD

**Issue by vandensd** [mdbootstrap/bootstrap-material-design#55]
Would be helpful either to have in the Github project and/or website a skeleton setup for SASS.  I'm a pro subscriber and have access to the admin example and it wasn't apparent that the vanilla mbd.css has been modified for the specific project templates.  Therefore it would be great to have a starting point to start from the initial scss files and have examples to modify the css using SASS for different projects.

**Comment by mattonit** [comment]
Hi, @vandensd 

I added this to our ideas list. I hope we'll create it soon

**Comment by Romainpetit** [comment]
Same need here. Trying to start using the SASS files called in my own tasks, with MDB as node dependency.

**Comment by siemiatj** [comment]
Bump. Webpack example would be great. I've wasted 2 days already trying to get this to build.

**Comment by PiotrObrebski** [comment]
You can explore and use our scss files in MDB-Gulp-Free_version package.
Pro users can have acces to all scss files in MDB-Gulp-Pro_version package.
There is always a mdb.scss file that display all our imported elements that are compiled into mdb.css.
You can find all needed information about this topic in our tutorial: https://mdbootstrap.com/education/bootstrap/gulp-installation/
