### ISSUE TITLE
[Feature Request] React support

### ISSUE THREAD

**Issue by nadeemja** [mdbootstrap/bootstrap-material-design#6]
Hello,

This looks like a great product, and I can't wait to use it.

However, will it work it React? 
Does it depend on jQuery?

**Comment by mdbootstrap** [comment]
Hi,

thank you for motivating words.

Right now it depends on jQuery. Of course it will work with any other library/framework but it still depends how you will manage it. As you have already noticed, it's not always recommended  to mix jQuery with React.
