### ISSUE TITLE
Alternate input field going out of column

### ISSUE THREAD

**Issue by bharath-bony** [mdbootstrap/bootstrap-material-design#60]
![image](https://cloud.githubusercontent.com/assets/17137372/25421758/e8dd0a82-2a7b-11e7-86e8-134a4b97307a.png)

**Comment by mattonit** [comment]
@bharath-bony I added this to our bug list and this will be fixed in the next version of MDB

**Comment by bharath-bony** [comment]
This issue can be fixed by adding 'text-indent' and removing the 15px left and right padding of the input field.

![untitled-2](https://user-images.githubusercontent.com/17137372/29600375-17fd0f72-87f3-11e7-9a4f-fdf5b38d9274.png)
