### ISSUE TITLE
Buttons and outlined button size mismatch

### ISSUE THREAD

**Issue by bharath-bony** [mdbootstrap/bootstrap-material-design#61]
The buttons and outlined buttons cannot be used at once in a row as the border in outlined button makes it look bigger than a normal button. If the border is given for buttons also it would be in the same size.

![image](https://cloud.githubusercontent.com/assets/17137372/25423209/71ade0ac-2a81-11e7-95a7-f718dc21f9de.png)

![image](https://cloud.githubusercontent.com/assets/17137372/25423390/244545ca-2a82-11e7-8781-b00c9240bdd1.png)

**Comment by mattonit** [comment]
I added this to our TODO list

**Comment by bharath-bony** [comment]
I found this issue has been fixed, Thanks.
