### ISSUE TITLE
Problem using input mask

### ISSUE THREAD

**Issue by GuilhermeProgrammer** [mdbootstrap/bootstrap-material-design#66]
I'm a pro mdb user, and I had a problem here, when I use a mask in the input, it does not have the expected performance.
For example, I have field:
![image](https://cloud.githubusercontent.com/assets/6062749/26754623/9998980a-4854-11e7-8c4c-8c9dba2802d6.png)

I added a mask in the field using maskMoney.js, when it gets the focus it gets:

![image](https://cloud.githubusercontent.com/assets/6062749/26754634/c29d2338-4854-11e7-909e-2fd7c298cb10.png)

But when I remove the focus if I do not type anything, the label still floats:

![image](https://cloud.githubusercontent.com/assets/6062749/26754643/e7cb9a86-4854-11e7-9cc9-5c990fd56937.png)

And if you type a value, it loses formatting by removing focus:

![image](https://cloud.githubusercontent.com/assets/6062749/26754658/0fd9eeb0-4855-11e7-9a9d-35ebc5f3f66f.png)

Is this normal or does it have a problem with mdb?
I await a return, thank you

**Comment by magdao-mdb** [comment]
Could you paste your code here, please? It would be much easier to figure our what's the problem.
