### ISSUE TITLE
how to load mdboostrap with reactJS?

### ISSUE THREAD

**Issue by apellanr** [mdbootstrap/bootstrap-material-design#68]
Is there any special instruction on how to load mdbootstrap components with React JS? The CDN does not seem to work well for me. Tried to upload the files directly into my components folder, but seems to make everything to haywire when compiling. 

Any advice from those who have used MDBootstrap with ReactJS would be appreciated!

**Comment by mattonit** [comment]
@apellanr, currently we don't support react. React will be supported in the future
