### ISSUE TITLE
Need to support right-to-left layout and navigation with all components instead of handy css?? ANY HELP

### ISSUE THREAD

**Issue by tomavic** [mdbootstrap/bootstrap-material-design#70]

**Comment by mattonit** [comment]
Currently, MDB doesn't support RTL. It's because Bootstrap doesn't support it itself. Please read more here: https://github.com/twbs/bootstrap/issues/19555

**Comment by tomavic** [comment]
I had already handled it. Thanks for fast replay!

**Comment by amjadyahya** [comment]
> I had already handled it. Thanks for fast replay!

How did you managed to do it?
