### ISSUE TITLE
TypeError: $(...).material_select is not a function

### ISSUE THREAD

**Issue by t9toqwerty** [mdbootstrap/bootstrap-material-design#71]
My Html Is 

    <div class="md-form">
    <i class="fa fa-bank prefix"></i>
    <select class="mdb-select" name="place"><option value="1">PLACE 1</option><option     value="2">PLACE 2</option></select>
    <label for="form3">Select Place</label>
    </div>

Scripts Inside the body 

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.2/js/mdb.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
    <script src="http://127.0.0.1:8000/js/all.js"></script>
    <script>
    $(document).ready(function () {
    new WOW().init();
    $('.mdb-select').material_select();
    });

**Comment by t9toqwerty** [comment]
Scripts Inside the body 

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.2/js/mdb.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
<script src="http://127.0.0.1:8000/js/all.js"></script>
<script>
    $(document).ready(function () {
        new WOW().init();
        $('.mdb-select').material_select();
    });
</script>`

**Comment by mattonit** [comment]
What's your version of MDB? Do you use free or pro version?

**Comment by miculprogramator** [comment]
i have same error

**Comment by mattonit** [comment]
@miculprogramator you're probably using the free version of MDB. Material Select is a premium component which isn't available in MDB Free

**Comment by raza2022** [comment]
so it's mean in free version users can't use the core component like select, WTF then we are doing on earth

**Comment by Martussky** [comment]
You can use a default select. Here, on the left side, you have a code: https://mdbootstrap.com/docs/jquery/forms/select/.

**Comment by yawaweb** [comment]
i have the same problem and i have the pro version

**Comment by IamJayshree** [comment]
> @miculprogramator you're probably using the free version of MDB. Material Select is a premium component which isn't available in MDB Free

sadly i understood this after wasting 3 precious hours
