### ISSUE TITLE
Dynamic font-family.

### ISSUE THREAD

**Issue by FaheemAlam** [mdbootstrap/bootstrap-material-design#72]
I am having an issue using different font-family then `Roboto`.
every thing is dynamic and can be controled using SCSS variables but i didn't understand why is `Roboto` is static 
https://github.com/mdbootstrap/bootstrap-material-design/blob/master/sass/mdb/free/_typography.scss#L3

it would be great if you make this font-family as dynamic, So that we can easily override if we need using only SCSS variable.

**Comment by mattonit** [comment]
Great idea! This will be added to 4.4.0

**Comment by FaheemAlam** [comment]
Thanks :)

**Comment by jeanmartin** [comment]
seems like it has not been..
