### ISSUE TITLE
sass compiling errors when working with mdb 4.4.0 & bootstrap 4.0.0-alpha.6

### ISSUE THREAD

**Issue by jenCape** [mdbootstrap/bootstrap-material-design#75]
I just replaced my local copy of mdb 4.3.0 with mdb 4.4.0, but `sass-loader` complains when i tried to compile mdb with bootstrap.

main.scss:
```
@import '../vendor/bootstrap/css/bootstrap';
@import '../vendor/mdbootstrap/sass/mdb';
```

error:
```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js?sourceMap!./src/css/main.scss
Module build failed: 
  0: (
    ^
      (x: 0, y: 0) isn't a valid CSS value.
      in /vendor/bootstrap/css/_variables.scss (line 145, column 6)
 @ ./src/css/main.scss 4:14-93
 @ ./src/js/main.js
```

this worked when I switched back to mdb 4.3.0, it also worked if I comment-out either of the two imports (so just `@import '../vendor/bootstrap/css/bootstrap';` or just `@import '../vendor/mdbootstrap/sass/mdb';`)

I'm compiling everything with webpack:
```
 ...
module: {
    rules: removeEmpty([
        {
            test: /\.scss$/,
            exclude: /node_modules/,
            use: [
                'style-loader',
                'css-loader',
                'sass-loader?sourceMap'
            ]
        }
    ])
}
...
```

**Comment by florantara** [comment]
Same here. Although I'm not using webpack. It's complaining about the same line from the bootstrap `_variables.scss` file.

**Comment by BFSzymanski** [comment]
That's because we do not use Alpha 6 in MDB 4.4.

As we wrote in change log (https://mdbootstrap.com/changelog/) we use experimental, not yet published  version of Bootstrap Beta.

And as we wrote in disclaimer - if you need a stable version you should you MDB 4.3.2 still available on our website.

**Comment by jenCape** [comment]
but all the examples on mdboostrap are updated to the 4.4 (at least the cards are now using `.card-body` instead of `.card-block`), do you still have 4.3 docs available somewhere?

also, how should we compile mdb 4.4? you've included `bootstrap.js` (though in the comments, it says `v4.0.0-alpha.6`, but i couldn't find the css files anywhere. and `normalize` appears to be missing without bootstrap

**Comment by BFSzymanski** [comment]
Although comment says "alpha-6" it's a newer version.

As we wrote in changelog - "Dropped Normalize.css for Reboot.css (which is actually built upon Normalize.css)"

You have 2 choices:

1. Use the newest, not yet published Bootstrap: https://github.com/twbs/bootstrap

2. Use stable MDB 4.3.2: http://mdbootstrap.com/legacy/4.3.2/
