### ISSUE TITLE
Bootstrap Update is required

### ISSUE THREAD

**Issue by ShilakhaLuthra** [mdbootstrap/bootstrap-material-design#76]
Hi Team,

I am having issue in collapse functionalities. I am using latest version of yours. Root cause is that this was a known issue in bootstrap 7 months back and you are using alpha 6 version of bootstrap. Bootstrap has fixed this issue 2/3 months back. Could you assist us by updating bootstrap to the latest version.

We have a client demo next week. Could you please assist me on this.

Kindly update me on shilakha.luthra@mavenwave.com

**Comment by mattonit** [comment]
In MDB 4.4 we don't use Alpha-6. However, the comment in `bootstrap.css` says that we use A6. We use the latest, experimental code of Bootstrap 4 beta 1. Here you can track the progress of Bootstrap Beta: https://github.com/twbs/bootstrap/milestone/41
