### ISSUE TITLE
get rid of utility classes that bootstrap 4 already have

### ISSUE THREAD

**Issue by dagman** [mdbootstrap/bootstrap-material-design#77]
at least get rid of spacing utility classes
different combos like `.py-4.py-lg-0` doesn't work as expected 
 _mdb.css_ goes after _bootstrap.css_ so `.py-4 `which _mdb.css_ also have included overrides `.py-lg-0` which is in _bootstrap.css_

inside you **_helpers.scss** file remove this script
```
@each $prop,
$abbrev in (margin: m, padding: p) {
    @each $size,
    $lengths in $spacers {
        $length-x: map-get($lengths, x);
        $length-y: map-get($lengths, y);
        .#{$abbrev}t-#{$size} {
            #{$prop}-top: $length-y !important;
        }
        .#{$abbrev}b-#{$size} {
            #{$prop}-bottom: $length-y !important;
        }
        .#{$abbrev}y-#{$size} {
            #{$prop}-top: $length-y !important;
            #{$prop}-bottom: $length-y !important;
        }
    }
}
```
I have commented it and spacing combos works as charm.

**Comment by mattonit** [comment]
This will be improved with next update
