### ISSUE TITLE
Dropdown right does not work in navbar

### ISSUE THREAD

**Issue by simivar** [mdbootstrap/bootstrap-material-design#79]
Because of this line in CSS:
`.navbar .dropdown-menu.dropdown-menu-right {
    right: auto !important;
}`

dropdown menu is out of screen: http://i.imgur.com/NODgBc2.png

**Comment by mattonit** [comment]
Could you please share code snippet with us?

**Comment by mattonit** [comment]
Closed due to no reply

**Comment by DeluxZ** [comment]
I can confirm this. I have the same behavior as in the image. When you use the code below you will see that the dropdown goes to the right, and out of the screen. Only on screens < 600px there is a css rule .dropdown-menu-right because of this on line `86` in `_navbar.scss`.

```scss
&.dropdown-menu-right {
      @media (max-width: $small-screen) {
        right: auto !important;
      }
    }
```

To make this work on screens < 600 this should be.

```scss
&.dropdown-menu-right {
      @media (max-width: $small-screen) {
        right: 0;
        left: auto;
      }
    }
```


```
<nav class="navbar fixed-top navbar-toggleable-sm navbar-expand-lg navbar-dark bg-grey darken-2 scrolling-navbar double-nav">
            <!-- SideNav slide-out button -->
            <div class="float-left">
                <a href="#" data-activates="slide-out" class="button-collapse mt-2">
                    <i class="fa fa-bars"></i>
                </a>
            </div>
            <ul class="nav navbar-nav nav-flex-icons ml-auto">
                <li class="nav-item avatar dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-light" id="navbarDropdownMenuLink-5" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-2.jpg" class="img-fluid rounded-circle z-depth-0">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-purple" aria-labelledby="navbarDropdownMenuLink-5">
                        <div class="row">
                            <div class="col">
                                <img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-2.jpg" class="img-fluid rounded-circle z-depth-0 flex-center">
                            </div>
                        </div>
                        <a class="dropdown-item waves-effect waves-light" href="#">Action</a>
                        <a class="dropdown-item waves-effect waves-light" href="#">Another action</a>
                        <a class="dropdown-item waves-effect waves-light" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
        </nav>

**Comment by micsan13br** [comment]
Hello mattonit, please re-open and fix this.

I bought yesterday the latest release and the bug is still there.
You can easily reproduce it on the latest chrome with a dropdown (right menu style) in the navbar.

Actually you don't really need a snippet because you can simply open https://mdbootstrap.com, scale down the window to about 400-500 px (mobile resolution) and click the PROFILE icon (at the top right).
The menu will be placed off-screen (probably right-aligned to the original width).

Also, are you sure you cannot achieve this without !important in CSS?
.navbar .dropdown-menu.dropdown-menu-right { right: auto!important; }

**Comment by simivar** [comment]
@mattonit: To see this bug simply:
1. Go to https://flyingcobra.sjar.net/. 
2. Scale down window to width >= 600 px.

Then you'll see: https://i.imgur.com/2MLi616.png 

Sorry for such delay on responding.

**Comment by micsan13br** [comment]
The issue appears closed and needs to be re-opened, otherwise collaborators will most likely not receive notifications or ignore it.

**Comment by mattonit** [comment]
@micsan13br I receive notifications for closed issues too :)

**Comment by mattonit** [comment]
What's your version of MDB? Do you use the latest update (4.5.0)?

**Comment by micsan13br** [comment]
Yes i'm on 4.5.0

**Comment by takutolehr** [comment]
There is another styling issue with dropdown-menu-right.

I use dropdown-menu-right class for navbar dropdown items that are aligned right.
https://i.imgur.com/SyHI5e3.png

But when the navbar is in mobile mode...
https://i.imgur.com/znZoTiO.png

I think this is why the original bootstrap does it with "position: static;".

**Comment by Martussky** [comment]
Hi,
update your MDB package to the newest version, it should help.
Best,
Marta

**Comment by takutolehr** [comment]
I just updated from MDB_PRO_4.5.5 to the latest MDB_PRO_4.5.6, and confirmed that my issue still exists.

I'm gonna keep using the following js workaround for now:

```
function fixNavDropdown() {
        if($( window ).width() <= 575) {
                $('.navbar .dropdown-menu').removeClass('dropdown-menu-right');
         } else {
                $('.navbar .dropdown-menu').addClass('dropdown-menu-right');
        }
}

$(window).resize(function() {
        fixNavDropdown();
});

fixNavDropdown();
```

**Comment by JackZeled0n** [comment]
> I just updated from MDB_PRO_4.5.5 to the latest MDB_PRO_4.5.6, and confirmed that my issue still exists.
> 
> I'm gonna keep using the following js workaround for now:
> 
> ```
> function fixNavDropdown() {
>         if($( window ).width() <= 575) {
>                 $('.navbar .dropdown-menu').removeClass('dropdown-menu-right');
>          } else {
>                 $('.navbar .dropdown-menu').addClass('dropdown-menu-right');
>         }
> }
> 
> $(window).resize(function() {
>         fixNavDropdown();
> });
> 
> fixNavDropdown();
> ```

this works for the angular version too

**Comment by micsan13br** [comment]
@mattonit is this issue still not fixed?

**Comment by JackZeled0n** [comment]
> 
> 
> @mattonit is this issue still not fixed?

This issue is fixed.
