### ISSUE TITLE
Waves creates i from input.btn

### ISSUE THREAD

**Issue by git-no** [mdbootstrap/bootstrap-material-design#8]
MDB Waves transfers HTML code

```
<input type="submit" class="btn btn-primary value="Submit">
```

into

```
<i class="btn btn-primary text-uppercase waves-input-wrapper waves-effect waves-light" style="color:rgb(255, 255, 255);background:rgba(0, 0, 0, 0)">
<input type="submit" class="waves-button-input" value="Send" style="background-color:rgba(0,0,0,0);">
</i>
```

This is wrong, the i tag should not exists.

**Comment by bf** [comment]
Status on this issue?

**Comment by cyimking** [comment]
Still an issue. It's converting each input button.

**Comment by Barvoj** [comment]
Any progress??

It is annoying because user has to click to small <input> text in big <i> element. Otherwise nothing happens.

**Comment by bf** [comment]
@Barvoj @cyimking  I've found so many bugs with mdbootstrap I am kind of regretting switching over to it. My current stacks is a mix between mdb and vanilla bootstrap 4 alpha through sass / webpack. You can throw most of the javascript functionality down the drain when using it in a modern React project.

**Comment by cyimking** [comment]
@bf Same here. Did you find a solution to this issue via JS?

**Comment by mattonit** [comment]
This will be fixed in MDB 4.4.0

**Comment by cyimking** [comment]
Found a temp solution.

mdb.js file
~ Line 5085, comment out the if statement (or remove the "input" element from the array)
```
  if (['input', 'img'].indexOf(tagName) !== -1) {
           TagWrapper[tagName](element);
            element = element.parentElement;
    }
```

~ Line 4788, comment out TagWrapper or comment out the input function:
```
 // Wrap <input> tag so it can perform the effect
 input: function (element) {...}

```

**Comment by mattonit** [comment]
It's finally fixed ;)

**Comment by cnocon** [comment]
@mattonit It's still an issue in our installation.

**Comment by repli2dev** [comment]
It is causing a trouble when integrating reCAPTCHA, after providing `class="g-recaptcha" data-sitekey="your_site_key"` the class is moved to the wrapper `i` element... then reCAPTCHA script fails.

**Comment by jrodl3r** [comment]
This is still an issue in 4.5.7 - **Please fix**

**Comment by MistaTwista** [comment]
confirm in 4.5.9

**Comment by pvaling** [comment]
Please fix. Pro 4.5.7

**Comment by adbir** [comment]
Still around today. Version 4.12.02
