### ISSUE TITLE
Suggestion: chat component

### ISSUE THREAD

**Issue by dcy** [mdbootstrap/bootstrap-material-design#80]
Hi!
It is better to have a component like [Chat-message](https://wrappixel.com/ampleadmin/ampleadmin-html/ampleadmin-minimal/chat.html) or [direct chat](https://adminlte.io/themes/AdminLTE/pages/widgets.html)

**Comment by mattonit** [comment]
@dcy thank you for your suggestion! We're already working on our new admin dashboard template so this will be a part of it

**Comment by dcy** [comment]
@mattonit Hello, is chat component ready? Which dashboard template has chat component?

**Comment by mattonit** [comment]
@dcy here you can see the preview from our Admin Dashboard: https://mdbootstrap.com/previews/templates/admin-dashboard/html/pages/chat.html

If you don't want to use our admin dashboard, here you can grab chat component: https://mdbootstrap.com/components/bootstrap-chat/

**Comment by dcy** [comment]
@mattonit Why bootstrap-chat  not show in left SideNav? Are there other components not show in navigation?

**Comment by mattonit** [comment]
@dcy, here you can find a full list of components: https://mdbootstrap.com/md-bootstrap-sitemap
