### ISSUE TITLE
mbd 3 documentation is missing for navbar

### ISSUE THREAD

**Issue by Ashwinvalento** [mdbootstrap/bootstrap-material-design#82]
the documentation for mdb3 nav bar redirects to mdb 4. 

The Url is as follows:

https://mdbootstrap.com/mdb3/getting-started-mdb3/

**Comment by mattonit** [comment]
Thank you for noticing. Here you can find navbar docs for MDB3: https://mdbootstrap.com/mdb3/components/navbar/
