### ISSUE TITLE
Class duplication of spacing utilities

### ISSUE THREAD

**Issue by NeonDevil** [mdbootstrap/bootstrap-material-design#84]
Some MDB 4.4.1 spacing utility classes no longer overrides bootstrap v4-beta classes and may be not be necesessary.

This is specific to margin and padding notations.

Reference:  
https://getbootstrap.com/docs/4.0/utilities/spacing/

**Comment by mattonit** [comment]
It's because we have added some additional classes for margins and paddings. We override Bootstrap's classes because we wanted to allow user to easily change the values of those classes
