### ISSUE TITLE
Add TS declaration (type definition) file for using the library within a TypeScript project

### ISSUE THREAD

**Issue by yaronuliel** [mdbootstrap/bootstrap-material-design#85]
It would be very useful to have a TypeScript declaration file (called mdb.d.ts for example) that contains the signatures of the JavaScript methods in the library.

Currently in order to integrate the library to a TypeScript project, the developer should create a patchy definition file - which should be maintained with every new version

**Comment by mattonit** [comment]
Thank you for letting us know. I added this to our ideas list

**Comment by agouveiac** [comment]
Hello, what is the status on the Typescript declaration file? Thank you.

**Comment by mattonit** [comment]
It's still in our TODO list

**Comment by fbjerggaard** [comment]
Any updates on this?

**Comment by skdeng** [comment]
Any update?

**Comment by Kizmar** [comment]
A type definition file could be used across all supported UI frameworks too... I'd love to see the priority kicked up on this one. ;)

**Comment by ascensus-mdb** [comment]
https://mdbootstrap.com/

**Comment by yaronuliel** [comment]
@gbujanski Why did you close the issue? is it resolved? ignored?
