### ISSUE TITLE
Navbar drop down menu not working with MDB 4.4.1

### ISSUE THREAD

**Issue by TheBobPony** [mdbootstrap/bootstrap-material-design#86]
I have upgraded from MDB 4.3.2 to MDB 4.4.1 and I have an issue with MDB 4.4.1's navbar, I can not view the drop down menu items. For proof: https://bobpony.org/beta/testing.html try clicking on the "dropdown" and there's no drop down items and I have tried clearing cache and same issue. Can you please look in to this? Also, I copied the navbar code from the documentation on the MDB website.

**Additional Information**
Browser: Google Chrome, version 60
Operating System: Windows 10

**Comment by mattonit** [comment]
It's because you forgot to include jQuery, Popper.js and Bootstrap
