### ISSUE TITLE
MDB Pro repo access

### ISSUE THREAD

**Issue by chimericdream** [mdbootstrap/bootstrap-material-design#88]
Would it be possible for people who have purchased MDB Pro to be granted read-only access to the Pro repository? I posted about this on the support board on the main site, but that hasn't garnered a response.

As a developer myself, I have a private repo with my own copy of MDB Pro, including patches and fixes for stability and whatnot. I'd rather submit a pull request to you than have to re-apply my own fixes for each new version.

**Comment by dawidadach** [comment]
Dear @chimericdream , 
We are finishing the setup of our own repository for PRO users. We need few more test to make sure it's reliable and stable, and we will share it with PRO license owners.

**Comment by chimericdream** [comment]
That's great to hear. But forgive me, what is there to test? If it is simply another GitHub repository, all you need is a mechanism for PRO license owners to provide their GitHub username to be given read-only access. Any forks of the repository will remain private, and if for some reason a person's access to the repo is revoked, any fork they might have is also revoked. If it's not a GitHub repo, why not? It's the simplest option and is very inexpensive ($7/mo for unlimited repos; plenty easy to cover given the price of an MDB PRO license). Managing some external private repository seems like unnecessary overhead.

**Comment by MaxCCC** [comment]
@dawidadach Is there some possibility to proxy to PRO releases? Here on github are releases and we're able to use are Artifactory as 'proxy' to get the releases we want. But now we've upgraded to PRO but we don't see a opportunity to do the same for the Pro packages.

**Comment by mdbootstrap** [comment]
Dear @chimericdream, 
as you noticed github charges 7$ / month for each user, therefore we would have to ask our customers to pay extra for the repository access. Instead, we have set up our own git server. Please contact us at office@mdbootstrap.com and our team will create an account for you. (please include order ID or email address which was used for making a purchase - that will speed up the process of verification and creation of account)
