### ISSUE TITLE
Variables not used in _navbars.scss

### ISSUE THREAD

**Issue by git-no** [mdbootstrap/bootstrap-material-design#9]
In _navbars.scss the colors are hard coded instead of refering to variables, e.g line 78 (navbar-light.active).
It would be worth to use the Bootstrap color variables instead. This would support customers to be capable of overriding values easily.

The Bootstrap variables are: 

```
$navbar-dark-color
$navbar-dark-hover-color
$navbar-dark-active-color
$navbar-dark-disabled-color

$navbar-light-color
$navbar-light-hover-color
$navbar-light-active-color
$navbar-light-disabled-color
```

**Comment by barcelona23** [comment]
Same in _buttons.scss & _colors.scss the colors are hard coded instead of refering to variables.
e.g line 470 $primary-color: #4285F4;

**Comment by mattonit** [comment]
Currently, we're preparing a new version of MDB, so we'll take a look at this
