### ISSUE TITLE
.navbar .dropdown-menu a:hover forced white in free version

### ISSUE THREAD

**Issue by tkuther** [mdbootstrap/bootstrap-material-design#90]
In the free version's mdb.css the a:hover color of dropdown-menus is somewhat distracting, especially as the default dropdown background itself is white, too, and the .dropdown-item:hover is light grey. The result is unreadable.

https://github.com/mdbootstrap/bootstrap-material-design/blob/2a57a03c7f7429fd4c575d425a25a681b65db6da/css/mdb.css#L5860

Makes sense for the premium material dropdowns, though.

**Comment by mattonit** [comment]
Hi, @tkuther!

Thanks for letting us know. I marked this as a bug so this will be fixed in the next version of MDB

**Comment by dfherr** [comment]
still unreadable

**Comment by Martussky** [comment]
We're working on a new release now and we remember about fixing this issue. If you want to fix this now, try this code:
`

.navbar .btn-group .dropdown-menu a:hover {
--
  | color: #000 !important;
  | }
  | .navbar .btn-group .dropdown-menu a:active {
  | color: #fff !important;
  | }

`

**Comment by SpeedHighway** [comment]
FYI, this also affects btn-links  If I have a button with class="btn btn-link", the color from btn (white) overrides the color from btn-link (black), and so the button is white on white, making it unreadable.

**Comment by Martussky** [comment]
I'm sorry this code doesn't work for you, I thought it will, but we will fix this issue in our next release which we are working now.
