### ISSUE TITLE
IE11 - flex-center issue

### ISSUE THREAD

**Issue by peterdanis** [mdbootstrap/bootstrap-material-design#93]
Hi,

flex-center is not working correctly in IE11. For me adding `flex-basis: 100%;` to `.flex-center` solved the issue.

```
<div class="view intro blue-gradient">
  <div class="full-bg-img">
    <div class="container white-text flex-center">
      <div class="row flex-center">
        <div class="col-8">
          <h2 class="animated fadeInDown" data-wow-delay="1s">About me</h2>
          <hr class="white animated fadeInLeft">
          <div class="animated fadeInUp">
            <p align="justify">It will always stay visible on the top, even when you scroll down</p>
            <p align="justify">Navbar's background will switch from transparent to solid color while scrolling down</p>
            <br>
            <p align="justify">Full page intro with background image will be always displayed in full screen mode, regardless of device </p>
          </div>
        </div>
        <div class="col-4">
          <img src="./public/img/profile-photo.pngs" alt="" class="img-fluid rounded-circle animated fadeInRight" style="max-height: 200px;">
        </div>
      </div>
    </div>
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/26599181/30692083-51696e8e-9eca-11e7-9473-8152982ad81d.png)

**Comment by mattonit** [comment]
Thanks for noticing and sharing your solution! This will be added to the next version of MDB ;)

**Comment by Martussky** [comment]
Hi peterdanis, you can try to change the place of the `.flex-center` class, remove and add it in different places, maybe it will work. But even Microsoft doesn't support IE in some cases, look at here: https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview .

**Comment by peterdanis** [comment]
Hi @Martussky , thanks for suggestion.

If I remember correctly, I have tried to add this class to a node higher in the DOM hierarchy, creating a dummy `<div>` and adding it there, but it did not work. Only adding `flex-basis: 100%` helped me to fix me issue.

**Comment by Martussky** [comment]
OK, we will try to fix this issue with MDB on IE in next release if it will be possible.

**Comment by ashleighmm** [comment]
Add width:100%!important inline on your row

**Comment by carlowahlstedt** [comment]
I tried adding the flex-basis that @peterdanis suggested but this affected other browsers, as did @ashleighmm width suggestion. However, I did find that adding the following worked for IE only:
`-ms-flex-preferred-size:100%`
Note that I wasn't using the specific scenario but rather have cards in a deck and they were rendering similar to the above image.
