### ISSUE TITLE
Horizontal stepper label misalignment

### ISSUE THREAD

**Issue by Saeven** [mdbootstrap/bootstrap-material-design#96]
The labels on the horizontal stepper are misaligned when you have several steps.  You can evidence this on your demo page too, by narrowing the view a bit to simulate the same circumstances:

![screenshot](https://i.imgur.com/G8b4Qo8.png)

https://mdbootstrap.com/components/bootstrap-steps-stepper/

**Comment by mattonit** [comment]
Works fine for me. Could you please re-check it?
![image](https://user-images.githubusercontent.com/4998725/32262699-50e6e6f4-bed6-11e7-9770-abc3a6873d46.png)
