### ISSUE TITLE
Releases of packages for Pro Edition 

### ISSUE THREAD

**Issue by MaxCCC** [mdbootstrap/bootstrap-material-design#97]
I've asked this question on the support forum but there was no response.
Here I can see the releases of MDBootstrap (Free).
https://github.com/mdbootstrap/bootstrap-material-design/releases

We use artifactory which functions as a 'proxy' when we setup a remote repo. We can do this for the releases of mdbootstrap on Github. 
Now we bought the PRO edition of mdbootstrap and we have access to a GitLab repo which contains the code of the PRO edition. The problem is there is no real tagging or release system over there.
Now we have downloaded the .zip we received after the purchase and deployed as local repo in Artifactory. But this is a manual solution and for each new version we will need to do this. Isn't it possible to put releases to on your GitLab environment so we can track it from there form our Artifactory?

**Comment by pglejzer** [comment]
we already have a tagging in our gitlab repo! I close this issue.
