### ISSUE TITLE
Styles not applying to DataTables

### ISSUE THREAD

**Issue by iamkumaranca** [mdbootstrap/bootstrap-material-design#98]
MDB styles aren't applying to the DataTables. It is applying the default bootstrap styles. It could be because of the recent update from DataTables for Bootstrap 4.

Also, the example doesn't mention materialize lib needs to be included for the drop-down. When included, it works but materialize colours are applied. Also, the normal drop-down doesn't hide so it shows 2 drop-downs.

[](https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js)
[](https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css)

**Comment by mattonit** [comment]
Could you please provide us more details? Any example code or live demo?
