### ISSUE TITLE
Navbar - Fixed Top - Main Content hidden

### ISSUE THREAD

**Issue by Juchar** [mdbootstrap/bootstrap-material-design#99]
Using a fixed top navbar will hide the main content.

See [here](https://mdbootstrap.com/previews/docs/latest/html/navbar/navbar-fixed-top.html) where the first `h1` is hidden.

Same behaviour for **Angular Material Design Bootstrap**.

**Comment by mattonit** [comment]
It's not a bug. It's intended behavior of Bootstrap. Anyway, we'll improve our preview page

**Comment by AbdulRehman3** [comment]
it can be avoided by adding 60px margin-bottom as;
.navbar{margin-bottom: 60px;}

**Comment by DavidRimar** [comment]
Hello, adding margins does the trick, however, I wouldnt call it a solution, it is just a work-around. It still does NOT change the fact that by adding "fixed-top" class for the navbar, the content goes BEHIND the navbar. The work-around requires specifying margins responsively through media queries, but even then, for specific bands of width (e.g. Extra small devices (portrait phones, less than 576px)), adding a fixed marging like 90px will only work for specific resolutions within that band. Overall, if this is the only way around this (not found any other solutions anywhere), I am still inclined to call it a bug. What's the benefit of having this behaviour?
